// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/dominant-strategies/go-quai/mesh_api/go"
)

func Start() {
	log.Printf("Server started")

	AccountAPIService := openapi.NewAccountAPIService()
	AccountAPIController := openapi.NewAccountAPIController(AccountAPIService)

	BlockAPIService := openapi.NewBlockAPIService()
	BlockAPIController := openapi.NewBlockAPIController(BlockAPIService)

	CallAPIService := openapi.NewCallAPIService()
	CallAPIController := openapi.NewCallAPIController(CallAPIService)

	ConstructionAPIService := openapi.NewConstructionAPIService()
	ConstructionAPIController := openapi.NewConstructionAPIController(ConstructionAPIService)

	EventsAPIService := openapi.NewEventsAPIService()
	EventsAPIController := openapi.NewEventsAPIController(EventsAPIService)

	MempoolAPIService := openapi.NewMempoolAPIService()
	MempoolAPIController := openapi.NewMempoolAPIController(MempoolAPIService)

	NetworkAPIService := openapi.NewNetworkAPIService()
	NetworkAPIController := openapi.NewNetworkAPIController(NetworkAPIService)

	SearchAPIService := openapi.NewSearchAPIService()
	SearchAPIController := openapi.NewSearchAPIController(SearchAPIService)

	router := openapi.NewRouter(AccountAPIController, BlockAPIController, CallAPIController, ConstructionAPIController, EventsAPIController, MempoolAPIController, NetworkAPIController, SearchAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
