// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi

import (
	"context"
	"net/http"
)



// AccountAPIRouter defines the required methods for binding the api requests to a responses for the AccountAPI
// The AccountAPIRouter implementation should parse necessary information from the http request,
// pass the data to a AccountAPIServicer to perform the required actions, then write the service results to the http response.
type AccountAPIRouter interface { 
	AccountBalance(http.ResponseWriter, *http.Request)
	AccountCoins(http.ResponseWriter, *http.Request)
}
// BlockAPIRouter defines the required methods for binding the api requests to a responses for the BlockAPI
// The BlockAPIRouter implementation should parse necessary information from the http request,
// pass the data to a BlockAPIServicer to perform the required actions, then write the service results to the http response.
type BlockAPIRouter interface { 
	Block(http.ResponseWriter, *http.Request)
	BlockTransaction(http.ResponseWriter, *http.Request)
}
// CallAPIRouter defines the required methods for binding the api requests to a responses for the CallAPI
// The CallAPIRouter implementation should parse necessary information from the http request,
// pass the data to a CallAPIServicer to perform the required actions, then write the service results to the http response.
type CallAPIRouter interface { 
	Call(http.ResponseWriter, *http.Request)
}
// ConstructionAPIRouter defines the required methods for binding the api requests to a responses for the ConstructionAPI
// The ConstructionAPIRouter implementation should parse necessary information from the http request,
// pass the data to a ConstructionAPIServicer to perform the required actions, then write the service results to the http response.
type ConstructionAPIRouter interface { 
	ConstructionDerive(http.ResponseWriter, *http.Request)
	ConstructionPreprocess(http.ResponseWriter, *http.Request)
	ConstructionMetadata(http.ResponseWriter, *http.Request)
	ConstructionPayloads(http.ResponseWriter, *http.Request)
	ConstructionCombine(http.ResponseWriter, *http.Request)
	ConstructionParse(http.ResponseWriter, *http.Request)
	ConstructionHash(http.ResponseWriter, *http.Request)
	ConstructionSubmit(http.ResponseWriter, *http.Request)
}
// EventsAPIRouter defines the required methods for binding the api requests to a responses for the EventsAPI
// The EventsAPIRouter implementation should parse necessary information from the http request,
// pass the data to a EventsAPIServicer to perform the required actions, then write the service results to the http response.
type EventsAPIRouter interface { 
	EventsBlocks(http.ResponseWriter, *http.Request)
}
// MempoolAPIRouter defines the required methods for binding the api requests to a responses for the MempoolAPI
// The MempoolAPIRouter implementation should parse necessary information from the http request,
// pass the data to a MempoolAPIServicer to perform the required actions, then write the service results to the http response.
type MempoolAPIRouter interface { 
	Mempool(http.ResponseWriter, *http.Request)
	MempoolTransaction(http.ResponseWriter, *http.Request)
}
// NetworkAPIRouter defines the required methods for binding the api requests to a responses for the NetworkAPI
// The NetworkAPIRouter implementation should parse necessary information from the http request,
// pass the data to a NetworkAPIServicer to perform the required actions, then write the service results to the http response.
type NetworkAPIRouter interface { 
	NetworkList(http.ResponseWriter, *http.Request)
	NetworkStatus(http.ResponseWriter, *http.Request)
	NetworkOptions(http.ResponseWriter, *http.Request)
}
// SearchAPIRouter defines the required methods for binding the api requests to a responses for the SearchAPI
// The SearchAPIRouter implementation should parse necessary information from the http request,
// pass the data to a SearchAPIServicer to perform the required actions, then write the service results to the http response.
type SearchAPIRouter interface { 
	SearchTransactions(http.ResponseWriter, *http.Request)
}


// AccountAPIServicer defines the api actions for the AccountAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type AccountAPIServicer interface { 
	AccountBalance(context.Context, AccountBalanceRequest) (ImplResponse, error)
	AccountCoins(context.Context, AccountCoinsRequest) (ImplResponse, error)
}


// BlockAPIServicer defines the api actions for the BlockAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type BlockAPIServicer interface { 
	Block(context.Context, BlockRequest) (ImplResponse, error)
	BlockTransaction(context.Context, BlockTransactionRequest) (ImplResponse, error)
}


// CallAPIServicer defines the api actions for the CallAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type CallAPIServicer interface { 
	Call(context.Context, CallRequest) (ImplResponse, error)
}


// ConstructionAPIServicer defines the api actions for the ConstructionAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type ConstructionAPIServicer interface { 
	ConstructionDerive(context.Context, ConstructionDeriveRequest) (ImplResponse, error)
	ConstructionPreprocess(context.Context, ConstructionPreprocessRequest) (ImplResponse, error)
	ConstructionMetadata(context.Context, ConstructionMetadataRequest) (ImplResponse, error)
	ConstructionPayloads(context.Context, ConstructionPayloadsRequest) (ImplResponse, error)
	ConstructionCombine(context.Context, ConstructionCombineRequest) (ImplResponse, error)
	ConstructionParse(context.Context, ConstructionParseRequest) (ImplResponse, error)
	ConstructionHash(context.Context, ConstructionHashRequest) (ImplResponse, error)
	ConstructionSubmit(context.Context, ConstructionSubmitRequest) (ImplResponse, error)
}


// EventsAPIServicer defines the api actions for the EventsAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type EventsAPIServicer interface { 
	EventsBlocks(context.Context, EventsBlocksRequest) (ImplResponse, error)
}


// MempoolAPIServicer defines the api actions for the MempoolAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type MempoolAPIServicer interface { 
	Mempool(context.Context, NetworkRequest) (ImplResponse, error)
	MempoolTransaction(context.Context, MempoolTransactionRequest) (ImplResponse, error)
}


// NetworkAPIServicer defines the api actions for the NetworkAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type NetworkAPIServicer interface { 
	NetworkList(context.Context, MetadataRequest) (ImplResponse, error)
	NetworkStatus(context.Context, NetworkRequest) (ImplResponse, error)
	NetworkOptions(context.Context, NetworkRequest) (ImplResponse, error)
}


// SearchAPIServicer defines the api actions for the SearchAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type SearchAPIServicer interface { 
	SearchTransactions(context.Context, SearchTransactionsRequest) (ImplResponse, error)
}
