// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"
)

// BlockAPIController binds http requests to an api service and writes the service results to the http response
type BlockAPIController struct {
	service BlockAPIServicer
	errorHandler ErrorHandler
}

// BlockAPIOption for how the controller is set up.
type BlockAPIOption func(*BlockAPIController)

// WithBlockAPIErrorHandler inject ErrorHandler into controller
func WithBlockAPIErrorHandler(h ErrorHandler) BlockAPIOption {
	return func(c *BlockAPIController) {
		c.errorHandler = h
	}
}

// NewBlockAPIController creates a default api controller
func NewBlockAPIController(s BlockAPIServicer, opts ...BlockAPIOption) *BlockAPIController {
	controller := &BlockAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the BlockAPIController
func (c *BlockAPIController) Routes() Routes {
	return Routes{
		"Block": Route{
			strings.ToUpper("Post"),
			"/block",
			c.Block,
		},
		"BlockTransaction": Route{
			strings.ToUpper("Post"),
			"/block/transaction",
			c.BlockTransaction,
		},
	}
}

// Block - Get a Block
func (c *BlockAPIController) Block(w http.ResponseWriter, r *http.Request) {
	var blockRequestParam BlockRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&blockRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertBlockRequestRequired(blockRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertBlockRequestConstraints(blockRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.Block(r.Context(), blockRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// BlockTransaction - Get a Block Transaction
func (c *BlockAPIController) BlockTransaction(w http.ResponseWriter, r *http.Request) {
	var blockTransactionRequestParam BlockTransactionRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&blockTransactionRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertBlockTransactionRequestRequired(blockTransactionRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertBlockTransactionRequestConstraints(blockTransactionRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.BlockTransaction(r.Context(), blockTransactionRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
