// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"
)

// ConstructionAPIController binds http requests to an api service and writes the service results to the http response
type ConstructionAPIController struct {
	service ConstructionAPIServicer
	errorHandler ErrorHandler
}

// ConstructionAPIOption for how the controller is set up.
type ConstructionAPIOption func(*ConstructionAPIController)

// WithConstructionAPIErrorHandler inject ErrorHandler into controller
func WithConstructionAPIErrorHandler(h ErrorHandler) ConstructionAPIOption {
	return func(c *ConstructionAPIController) {
		c.errorHandler = h
	}
}

// NewConstructionAPIController creates a default api controller
func NewConstructionAPIController(s ConstructionAPIServicer, opts ...ConstructionAPIOption) *ConstructionAPIController {
	controller := &ConstructionAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the ConstructionAPIController
func (c *ConstructionAPIController) Routes() Routes {
	return Routes{
		"ConstructionDerive": Route{
			strings.ToUpper("Post"),
			"/construction/derive",
			c.ConstructionDerive,
		},
		"ConstructionPreprocess": Route{
			strings.ToUpper("Post"),
			"/construction/preprocess",
			c.ConstructionPreprocess,
		},
		"ConstructionMetadata": Route{
			strings.ToUpper("Post"),
			"/construction/metadata",
			c.ConstructionMetadata,
		},
		"ConstructionPayloads": Route{
			strings.ToUpper("Post"),
			"/construction/payloads",
			c.ConstructionPayloads,
		},
		"ConstructionCombine": Route{
			strings.ToUpper("Post"),
			"/construction/combine",
			c.ConstructionCombine,
		},
		"ConstructionParse": Route{
			strings.ToUpper("Post"),
			"/construction/parse",
			c.ConstructionParse,
		},
		"ConstructionHash": Route{
			strings.ToUpper("Post"),
			"/construction/hash",
			c.ConstructionHash,
		},
		"ConstructionSubmit": Route{
			strings.ToUpper("Post"),
			"/construction/submit",
			c.ConstructionSubmit,
		},
	}
}

// ConstructionDerive - Derive an AccountIdentifier from a PublicKey
func (c *ConstructionAPIController) ConstructionDerive(w http.ResponseWriter, r *http.Request) {
	var constructionDeriveRequestParam ConstructionDeriveRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&constructionDeriveRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertConstructionDeriveRequestRequired(constructionDeriveRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertConstructionDeriveRequestConstraints(constructionDeriveRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.ConstructionDerive(r.Context(), constructionDeriveRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// ConstructionPreprocess - Create a Request to Fetch Metadata
func (c *ConstructionAPIController) ConstructionPreprocess(w http.ResponseWriter, r *http.Request) {
	var constructionPreprocessRequestParam ConstructionPreprocessRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&constructionPreprocessRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertConstructionPreprocessRequestRequired(constructionPreprocessRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertConstructionPreprocessRequestConstraints(constructionPreprocessRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.ConstructionPreprocess(r.Context(), constructionPreprocessRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// ConstructionMetadata - Get Metadata for Transaction Construction
func (c *ConstructionAPIController) ConstructionMetadata(w http.ResponseWriter, r *http.Request) {
	var constructionMetadataRequestParam ConstructionMetadataRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&constructionMetadataRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertConstructionMetadataRequestRequired(constructionMetadataRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertConstructionMetadataRequestConstraints(constructionMetadataRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.ConstructionMetadata(r.Context(), constructionMetadataRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// ConstructionPayloads - Generate an Unsigned Transaction and Signing Payloads
func (c *ConstructionAPIController) ConstructionPayloads(w http.ResponseWriter, r *http.Request) {
	var constructionPayloadsRequestParam ConstructionPayloadsRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&constructionPayloadsRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertConstructionPayloadsRequestRequired(constructionPayloadsRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertConstructionPayloadsRequestConstraints(constructionPayloadsRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.ConstructionPayloads(r.Context(), constructionPayloadsRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// ConstructionCombine - Create Network Transaction from Signatures
func (c *ConstructionAPIController) ConstructionCombine(w http.ResponseWriter, r *http.Request) {
	var constructionCombineRequestParam ConstructionCombineRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&constructionCombineRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertConstructionCombineRequestRequired(constructionCombineRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertConstructionCombineRequestConstraints(constructionCombineRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.ConstructionCombine(r.Context(), constructionCombineRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// ConstructionParse - Parse a Transaction
func (c *ConstructionAPIController) ConstructionParse(w http.ResponseWriter, r *http.Request) {
	var constructionParseRequestParam ConstructionParseRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&constructionParseRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertConstructionParseRequestRequired(constructionParseRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertConstructionParseRequestConstraints(constructionParseRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.ConstructionParse(r.Context(), constructionParseRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// ConstructionHash - Get the Hash of a Signed Transaction
func (c *ConstructionAPIController) ConstructionHash(w http.ResponseWriter, r *http.Request) {
	var constructionHashRequestParam ConstructionHashRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&constructionHashRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertConstructionHashRequestRequired(constructionHashRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertConstructionHashRequestConstraints(constructionHashRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.ConstructionHash(r.Context(), constructionHashRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// ConstructionSubmit - Submit a Signed Transaction
func (c *ConstructionAPIController) ConstructionSubmit(w http.ResponseWriter, r *http.Request) {
	var constructionSubmitRequestParam ConstructionSubmitRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&constructionSubmitRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertConstructionSubmitRequestRequired(constructionSubmitRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertConstructionSubmitRequestConstraints(constructionSubmitRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.ConstructionSubmit(r.Context(), constructionSubmitRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
