// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// MempoolAPIService is a service that implements the logic for the MempoolAPIServicer
// This service should implement the business logic for every endpoint for the MempoolAPI API.
// Include any external packages or services that will be required by this service.
type MempoolAPIService struct {
}

// NewMempoolAPIService creates a default api service
func NewMempoolAPIService() *MempoolAPIService {
	return &MempoolAPIService{}
}

// Mempool - Get All Mempool Transactions
func (s *MempoolAPIService) Mempool(ctx context.Context, networkRequest NetworkRequest) (ImplResponse, error) {
	// TODO - update Mempool with the required logic for this service method.
	// Add api_mempool_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, MempoolResponse{}) or use other options such as http.Ok ...
	// return Response(200, MempoolResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Mempool method not implemented")
}

// MempoolTransaction - Get a Mempool Transaction
func (s *MempoolAPIService) MempoolTransaction(ctx context.Context, mempoolTransactionRequest MempoolTransactionRequest) (ImplResponse, error) {
	// TODO - update MempoolTransaction with the required logic for this service method.
	// Add api_mempool_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, MempoolTransactionResponse{}) or use other options such as http.Ok ...
	// return Response(200, MempoolTransactionResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("MempoolTransaction method not implemented")
}
