// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// BlockAPIService is a service that implements the logic for the BlockAPIServicer
// This service should implement the business logic for every endpoint for the BlockAPI API.
// Include any external packages or services that will be required by this service.
type BlockAPIService struct {
}

// NewBlockAPIService creates a default api service
func NewBlockAPIService() *BlockAPIService {
	return &BlockAPIService{}
}

// Block - Get a Block
func (s *BlockAPIService) Block(ctx context.Context, blockRequest BlockRequest) (ImplResponse, error) {
	// TODO - update Block with the required logic for this service method.
	// Add api_block_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, BlockResponse{}) or use other options such as http.Ok ...
	// return Response(200, BlockResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Block method not implemented")
}

// BlockTransaction - Get a Block Transaction
func (s *BlockAPIService) BlockTransaction(ctx context.Context, blockTransactionRequest BlockTransactionRequest) (ImplResponse, error) {
	// TODO - update BlockTransaction with the required logic for this service method.
	// Add api_block_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, BlockTransactionResponse{}) or use other options such as http.Ok ...
	// return Response(200, BlockTransactionResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("BlockTransaction method not implemented")
}
