// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// SearchAPIService is a service that implements the logic for the SearchAPIServicer
// This service should implement the business logic for every endpoint for the SearchAPI API.
// Include any external packages or services that will be required by this service.
type SearchAPIService struct {
}

// NewSearchAPIService creates a default api service
func NewSearchAPIService() *SearchAPIService {
	return &SearchAPIService{}
}

// SearchTransactions - [INDEXER] Search for Transactions
func (s *SearchAPIService) SearchTransactions(ctx context.Context, searchTransactionsRequest SearchTransactionsRequest) (ImplResponse, error) {
	// TODO - update SearchTransactions with the required logic for this service method.
	// Add api_search_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, SearchTransactionsResponse{}) or use other options such as http.Ok ...
	// return Response(200, SearchTransactionsResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("SearchTransactions method not implemented")
}
