// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// ConstructionAPIService is a service that implements the logic for the ConstructionAPIServicer
// This service should implement the business logic for every endpoint for the ConstructionAPI API.
// Include any external packages or services that will be required by this service.
type ConstructionAPIService struct {
}

// NewConstructionAPIService creates a default api service
func NewConstructionAPIService() *ConstructionAPIService {
	return &ConstructionAPIService{}
}

// ConstructionDerive - Derive an AccountIdentifier from a PublicKey
func (s *ConstructionAPIService) ConstructionDerive(ctx context.Context, constructionDeriveRequest ConstructionDeriveRequest) (ImplResponse, error) {
	// TODO - update ConstructionDerive with the required logic for this service method.
	// Add api_construction_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ConstructionDeriveResponse{}) or use other options such as http.Ok ...
	// return Response(200, ConstructionDeriveResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ConstructionDerive method not implemented")
}

// ConstructionPreprocess - Create a Request to Fetch Metadata
func (s *ConstructionAPIService) ConstructionPreprocess(ctx context.Context, constructionPreprocessRequest ConstructionPreprocessRequest) (ImplResponse, error) {
	// TODO - update ConstructionPreprocess with the required logic for this service method.
	// Add api_construction_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ConstructionPreprocessResponse{}) or use other options such as http.Ok ...
	// return Response(200, ConstructionPreprocessResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ConstructionPreprocess method not implemented")
}

// ConstructionMetadata - Get Metadata for Transaction Construction
func (s *ConstructionAPIService) ConstructionMetadata(ctx context.Context, constructionMetadataRequest ConstructionMetadataRequest) (ImplResponse, error) {
	// TODO - update ConstructionMetadata with the required logic for this service method.
	// Add api_construction_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ConstructionMetadataResponse{}) or use other options such as http.Ok ...
	// return Response(200, ConstructionMetadataResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ConstructionMetadata method not implemented")
}

// ConstructionPayloads - Generate an Unsigned Transaction and Signing Payloads
func (s *ConstructionAPIService) ConstructionPayloads(ctx context.Context, constructionPayloadsRequest ConstructionPayloadsRequest) (ImplResponse, error) {
	// TODO - update ConstructionPayloads with the required logic for this service method.
	// Add api_construction_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ConstructionPayloadsResponse{}) or use other options such as http.Ok ...
	// return Response(200, ConstructionPayloadsResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ConstructionPayloads method not implemented")
}

// ConstructionCombine - Create Network Transaction from Signatures
func (s *ConstructionAPIService) ConstructionCombine(ctx context.Context, constructionCombineRequest ConstructionCombineRequest) (ImplResponse, error) {
	// TODO - update ConstructionCombine with the required logic for this service method.
	// Add api_construction_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ConstructionCombineResponse{}) or use other options such as http.Ok ...
	// return Response(200, ConstructionCombineResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ConstructionCombine method not implemented")
}

// ConstructionParse - Parse a Transaction
func (s *ConstructionAPIService) ConstructionParse(ctx context.Context, constructionParseRequest ConstructionParseRequest) (ImplResponse, error) {
	// TODO - update ConstructionParse with the required logic for this service method.
	// Add api_construction_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ConstructionParseResponse{}) or use other options such as http.Ok ...
	// return Response(200, ConstructionParseResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ConstructionParse method not implemented")
}

// ConstructionHash - Get the Hash of a Signed Transaction
func (s *ConstructionAPIService) ConstructionHash(ctx context.Context, constructionHashRequest ConstructionHashRequest) (ImplResponse, error) {
	// TODO - update ConstructionHash with the required logic for this service method.
	// Add api_construction_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, TransactionIdentifierResponse{}) or use other options such as http.Ok ...
	// return Response(200, TransactionIdentifierResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ConstructionHash method not implemented")
}

// ConstructionSubmit - Submit a Signed Transaction
func (s *ConstructionAPIService) ConstructionSubmit(ctx context.Context, constructionSubmitRequest ConstructionSubmitRequest) (ImplResponse, error) {
	// TODO - update ConstructionSubmit with the required logic for this service method.
	// Add api_construction_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, TransactionIdentifierResponse{}) or use other options such as http.Ok ...
	// return Response(200, TransactionIdentifierResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ConstructionSubmit method not implemented")
}
