// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// AccountAPIService is a service that implements the logic for the AccountAPIServicer
// This service should implement the business logic for every endpoint for the AccountAPI API.
// Include any external packages or services that will be required by this service.
type AccountAPIService struct {
}

// NewAccountAPIService creates a default api service
func NewAccountAPIService() *AccountAPIService {
	return &AccountAPIService{}
}

// AccountBalance - Get an Account&#39;s Balance
func (s *AccountAPIService) AccountBalance(ctx context.Context, accountBalanceRequest AccountBalanceRequest) (ImplResponse, error) {
	// TODO - update AccountBalance with the required logic for this service method.
	// Add api_account_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, AccountBalanceResponse{}) or use other options such as http.Ok ...
	// return Response(200, AccountBalanceResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("AccountBalance method not implemented")
}

// AccountCoins - Get an Account&#39;s Unspent Coins
func (s *AccountAPIService) AccountCoins(ctx context.Context, accountCoinsRequest AccountCoinsRequest) (ImplResponse, error) {
	// TODO - update AccountCoins with the required logic for this service method.
	// Add api_account_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, AccountCoinsResponse{}) or use other options such as http.Ok ...
	// return Response(200, AccountCoinsResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("AccountCoins method not implemented")
}
