// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"
)

// AccountAPIController binds http requests to an api service and writes the service results to the http response
type AccountAPIController struct {
	service AccountAPIServicer
	errorHandler ErrorHandler
}

// AccountAPIOption for how the controller is set up.
type AccountAPIOption func(*AccountAPIController)

// WithAccountAPIErrorHandler inject ErrorHandler into controller
func WithAccountAPIErrorHandler(h ErrorHandler) AccountAPIOption {
	return func(c *AccountAPIController) {
		c.errorHandler = h
	}
}

// NewAccountAPIController creates a default api controller
func NewAccountAPIController(s AccountAPIServicer, opts ...AccountAPIOption) *AccountAPIController {
	controller := &AccountAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the AccountAPIController
func (c *AccountAPIController) Routes() Routes {
	return Routes{
		"AccountBalance": Route{
			strings.ToUpper("Post"),
			"/account/balance",
			c.AccountBalance,
		},
		"AccountCoins": Route{
			strings.ToUpper("Post"),
			"/account/coins",
			c.AccountCoins,
		},
	}
}

// AccountBalance - Get an Account's Balance
func (c *AccountAPIController) AccountBalance(w http.ResponseWriter, r *http.Request) {
	var accountBalanceRequestParam AccountBalanceRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&accountBalanceRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertAccountBalanceRequestRequired(accountBalanceRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertAccountBalanceRequestConstraints(accountBalanceRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.AccountBalance(r.Context(), accountBalanceRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// AccountCoins - Get an Account's Unspent Coins
func (c *AccountAPIController) AccountCoins(w http.ResponseWriter, r *http.Request) {
	var accountCoinsRequestParam AccountCoinsRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&accountCoinsRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertAccountCoinsRequestRequired(accountCoinsRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertAccountCoinsRequestConstraints(accountCoinsRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.AccountCoins(r.Context(), accountCoinsRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
