// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"
)

// CallAPIController binds http requests to an api service and writes the service results to the http response
type CallAPIController struct {
	service CallAPIServicer
	errorHandler ErrorHandler
}

// CallAPIOption for how the controller is set up.
type CallAPIOption func(*CallAPIController)

// WithCallAPIErrorHandler inject ErrorHandler into controller
func WithCallAPIErrorHandler(h ErrorHandler) CallAPIOption {
	return func(c *CallAPIController) {
		c.errorHandler = h
	}
}

// NewCallAPIController creates a default api controller
func NewCallAPIController(s CallAPIServicer, opts ...CallAPIOption) *CallAPIController {
	controller := &CallAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the CallAPIController
func (c *CallAPIController) Routes() Routes {
	return Routes{
		"Call": Route{
			strings.ToUpper("Post"),
			"/call",
			c.Call,
		},
	}
}

// Call - Make a Network-Specific Procedure Call
func (c *CallAPIController) Call(w http.ResponseWriter, r *http.Request) {
	var callRequestParam CallRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&callRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertCallRequestRequired(callRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertCallRequestConstraints(callRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.Call(r.Context(), callRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
