// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"
)

// NetworkAPIController binds http requests to an api service and writes the service results to the http response
type NetworkAPIController struct {
	service NetworkAPIServicer
	errorHandler ErrorHandler
}

// NetworkAPIOption for how the controller is set up.
type NetworkAPIOption func(*NetworkAPIController)

// WithNetworkAPIErrorHandler inject ErrorHandler into controller
func WithNetworkAPIErrorHandler(h ErrorHandler) NetworkAPIOption {
	return func(c *NetworkAPIController) {
		c.errorHandler = h
	}
}

// NewNetworkAPIController creates a default api controller
func NewNetworkAPIController(s NetworkAPIServicer, opts ...NetworkAPIOption) *NetworkAPIController {
	controller := &NetworkAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the NetworkAPIController
func (c *NetworkAPIController) Routes() Routes {
	return Routes{
		"NetworkList": Route{
			strings.ToUpper("Post"),
			"/network/list",
			c.NetworkList,
		},
		"NetworkStatus": Route{
			strings.ToUpper("Post"),
			"/network/status",
			c.NetworkStatus,
		},
		"NetworkOptions": Route{
			strings.ToUpper("Post"),
			"/network/options",
			c.NetworkOptions,
		},
	}
}

// NetworkList - Get List of Available Networks
func (c *NetworkAPIController) NetworkList(w http.ResponseWriter, r *http.Request) {
	var metadataRequestParam MetadataRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&metadataRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertMetadataRequestRequired(metadataRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertMetadataRequestConstraints(metadataRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.NetworkList(r.Context(), metadataRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// NetworkStatus - Get Network Status
func (c *NetworkAPIController) NetworkStatus(w http.ResponseWriter, r *http.Request) {
	var networkRequestParam NetworkRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&networkRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertNetworkRequestRequired(networkRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertNetworkRequestConstraints(networkRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.NetworkStatus(r.Context(), networkRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// NetworkOptions - Get Network Options
func (c *NetworkAPIController) NetworkOptions(w http.ResponseWriter, r *http.Request) {
	var networkRequestParam NetworkRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&networkRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertNetworkRequestRequired(networkRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertNetworkRequestConstraints(networkRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.NetworkOptions(r.Context(), networkRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
