// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// NetworkAPIService is a service that implements the logic for the NetworkAPIServicer
// This service should implement the business logic for every endpoint for the NetworkAPI API.
// Include any external packages or services that will be required by this service.
type NetworkAPIService struct {
}

// NewNetworkAPIService creates a default api service
func NewNetworkAPIService() *NetworkAPIService {
	return &NetworkAPIService{}
}

// NetworkList - Get List of Available Networks
func (s *NetworkAPIService) NetworkList(ctx context.Context, metadataRequest MetadataRequest) (ImplResponse, error) {
	// TODO - update NetworkList with the required logic for this service method.
	// Add api_network_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, NetworkListResponse{}) or use other options such as http.Ok ...
	// return Response(200, NetworkListResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("NetworkList method not implemented")
}

// NetworkStatus - Get Network Status
func (s *NetworkAPIService) NetworkStatus(ctx context.Context, networkRequest NetworkRequest) (ImplResponse, error) {
	// TODO - update NetworkStatus with the required logic for this service method.
	// Add api_network_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, NetworkStatusResponse{}) or use other options such as http.Ok ...
	// return Response(200, NetworkStatusResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("NetworkStatus method not implemented")
}

// NetworkOptions - Get Network Options
func (s *NetworkAPIService) NetworkOptions(ctx context.Context, networkRequest NetworkRequest) (ImplResponse, error) {
	// TODO - update NetworkOptions with the required logic for this service method.
	// Add api_network_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, NetworkOptionsResponse{}) or use other options such as http.Ok ...
	// return Response(200, NetworkOptionsResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("NetworkOptions method not implemented")
}
