// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// CallAPIService is a service that implements the logic for the CallAPIServicer
// This service should implement the business logic for every endpoint for the CallAPI API.
// Include any external packages or services that will be required by this service.
type CallAPIService struct {
}

// NewCallAPIService creates a default api service
func NewCallAPIService() *CallAPIService {
	return &CallAPIService{}
}

// Call - Make a Network-Specific Procedure Call
func (s *CallAPIService) Call(ctx context.Context, callRequest CallRequest) (ImplResponse, error) {
	// TODO - update Call with the required logic for this service method.
	// Add api_call_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, CallResponse{}) or use other options such as http.Ok ...
	// return Response(200, CallResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call method not implemented")
}
