// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// EventsAPIService is a service that implements the logic for the EventsAPIServicer
// This service should implement the business logic for every endpoint for the EventsAPI API.
// Include any external packages or services that will be required by this service.
type EventsAPIService struct {
}

// NewEventsAPIService creates a default api service
func NewEventsAPIService() *EventsAPIService {
	return &EventsAPIService{}
}

// EventsBlocks - [INDEXER] Get a range of BlockEvents
func (s *EventsAPIService) EventsBlocks(ctx context.Context, eventsBlocksRequest EventsBlocksRequest) (ImplResponse, error) {
	// TODO - update EventsBlocks with the required logic for this service method.
	// Add api_events_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, EventsBlocksResponse{}) or use other options such as http.Ok ...
	// return Response(200, EventsBlocksResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("EventsBlocks method not implemented")
}
