// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"
)

// MempoolAPIController binds http requests to an api service and writes the service results to the http response
type MempoolAPIController struct {
	service MempoolAPIServicer
	errorHandler ErrorHandler
}

// MempoolAPIOption for how the controller is set up.
type MempoolAPIOption func(*MempoolAPIController)

// WithMempoolAPIErrorHandler inject ErrorHandler into controller
func WithMempoolAPIErrorHandler(h ErrorHandler) MempoolAPIOption {
	return func(c *MempoolAPIController) {
		c.errorHandler = h
	}
}

// NewMempoolAPIController creates a default api controller
func NewMempoolAPIController(s MempoolAPIServicer, opts ...MempoolAPIOption) *MempoolAPIController {
	controller := &MempoolAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the MempoolAPIController
func (c *MempoolAPIController) Routes() Routes {
	return Routes{
		"Mempool": Route{
			strings.ToUpper("Post"),
			"/mempool",
			c.Mempool,
		},
		"MempoolTransaction": Route{
			strings.ToUpper("Post"),
			"/mempool/transaction",
			c.MempoolTransaction,
		},
	}
}

// Mempool - Get All Mempool Transactions
func (c *MempoolAPIController) Mempool(w http.ResponseWriter, r *http.Request) {
	var networkRequestParam NetworkRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&networkRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertNetworkRequestRequired(networkRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertNetworkRequestConstraints(networkRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.Mempool(r.Context(), networkRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// MempoolTransaction - Get a Mempool Transaction
func (c *MempoolAPIController) MempoolTransaction(w http.ResponseWriter, r *http.Request) {
	var mempoolTransactionRequestParam MempoolTransactionRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&mempoolTransactionRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertMempoolTransactionRequestRequired(mempoolTransactionRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertMempoolTransactionRequestConstraints(mempoolTransactionRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.MempoolTransaction(r.Context(), mempoolTransactionRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
