// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// ConstructionDeriveResponse - ConstructionDeriveResponse is returned by the `/construction/derive` endpoint.
type ConstructionDeriveResponse struct {

	// [DEPRECATED by `account_identifier` in `v1.4.4`] Address in network-specific format.
	Address string `json:"address,omitempty"`

	AccountIdentifier AccountIdentifier `json:"account_identifier,omitempty"`

	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// AssertConstructionDeriveResponseRequired checks if the required fields are not zero-ed
func AssertConstructionDeriveResponseRequired(obj ConstructionDeriveResponse) error {
	if err := AssertAccountIdentifierRequired(obj.AccountIdentifier); err != nil {
		return err
	}
	return nil
}

// AssertConstructionDeriveResponseConstraints checks if the values respects the defined constraints
func AssertConstructionDeriveResponseConstraints(obj ConstructionDeriveResponse) error {
	if err := AssertAccountIdentifierConstraints(obj.AccountIdentifier); err != nil {
		return err
	}
	return nil
}
