// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi


import (
	"errors"
)



// NetworkStatusResponse - NetworkStatusResponse contains basic information about the node's view of a blockchain network. It is assumed that any BlockIdentifier.Index less than or equal to CurrentBlockIdentifier.Index can be queried. If a Rosetta implementation prunes historical state, it should populate the optional `oldest_block_identifier` field with the oldest block available to query. If this is not populated, it is assumed that the `genesis_block_identifier` is the oldest queryable block. If a Rosetta implementation performs some pre-sync before it is possible to query blocks, sync_status should be populated so that clients can still monitor healthiness. Without this field, it may appear that the implementation is stuck syncing and needs to be terminated.
type NetworkStatusResponse struct {

	CurrentBlockIdentifier BlockIdentifier `json:"current_block_identifier"`

	// The timestamp of the block in milliseconds since the Unix Epoch. The timestamp is stored in milliseconds because some blockchains produce blocks more often than once a second.
	CurrentBlockTimestamp int64 `json:"current_block_timestamp"`

	GenesisBlockIdentifier BlockIdentifier `json:"genesis_block_identifier"`

	OldestBlockIdentifier BlockIdentifier `json:"oldest_block_identifier,omitempty"`

	SyncStatus SyncStatus `json:"sync_status,omitempty"`

	Peers []Peer `json:"peers,omitempty"`
}

// AssertNetworkStatusResponseRequired checks if the required fields are not zero-ed
func AssertNetworkStatusResponseRequired(obj NetworkStatusResponse) error {
	elements := map[string]interface{}{
		"current_block_identifier": obj.CurrentBlockIdentifier,
		"current_block_timestamp": obj.CurrentBlockTimestamp,
		"genesis_block_identifier": obj.GenesisBlockIdentifier,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertBlockIdentifierRequired(obj.CurrentBlockIdentifier); err != nil {
		return err
	}
	if err := AssertBlockIdentifierRequired(obj.GenesisBlockIdentifier); err != nil {
		return err
	}
	if err := AssertBlockIdentifierRequired(obj.OldestBlockIdentifier); err != nil {
		return err
	}
	if err := AssertSyncStatusRequired(obj.SyncStatus); err != nil {
		return err
	}
	for _, el := range obj.Peers {
		if err := AssertPeerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertNetworkStatusResponseConstraints checks if the values respects the defined constraints
func AssertNetworkStatusResponseConstraints(obj NetworkStatusResponse) error {
	if err := AssertBlockIdentifierConstraints(obj.CurrentBlockIdentifier); err != nil {
		return err
	}
	if obj.CurrentBlockTimestamp < 0 {
		return &ParsingError{Param: "CurrentBlockTimestamp", Err: errors.New(errMsgMinValueConstraint)}
	}
	if err := AssertBlockIdentifierConstraints(obj.GenesisBlockIdentifier); err != nil {
		return err
	}
	if err := AssertBlockIdentifierConstraints(obj.OldestBlockIdentifier); err != nil {
		return err
	}
	if err := AssertSyncStatusConstraints(obj.SyncStatus); err != nil {
		return err
	}
	for _, el := range obj.Peers {
		if err := AssertPeerConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
