// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// ConstructionPreprocessRequest - ConstructionPreprocessRequest is passed to the `/construction/preprocess` endpoint so that a Rosetta implementation can determine which metadata it needs to request for construction. Metadata provided in this object should NEVER be a product of live data (i.e. the caller must follow some network-specific data fetching strategy outside of the Construction API to populate required Metadata). If live data is required for construction, it MUST be fetched in the call to `/construction/metadata`.
type ConstructionPreprocessRequest struct {

	NetworkIdentifier NetworkIdentifier `json:"network_identifier"`

	Operations []Operation `json:"operations"`

	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// AssertConstructionPreprocessRequestRequired checks if the required fields are not zero-ed
func AssertConstructionPreprocessRequestRequired(obj ConstructionPreprocessRequest) error {
	elements := map[string]interface{}{
		"network_identifier": obj.NetworkIdentifier,
		"operations": obj.Operations,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertNetworkIdentifierRequired(obj.NetworkIdentifier); err != nil {
		return err
	}
	for _, el := range obj.Operations {
		if err := AssertOperationRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertConstructionPreprocessRequestConstraints checks if the values respects the defined constraints
func AssertConstructionPreprocessRequestConstraints(obj ConstructionPreprocessRequest) error {
	if err := AssertNetworkIdentifierConstraints(obj.NetworkIdentifier); err != nil {
		return err
	}
	for _, el := range obj.Operations {
		if err := AssertOperationConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
