// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// BlockTransactionRequest - A BlockTransactionRequest is used to fetch a Transaction included in a block that is not returned in a BlockResponse.
type BlockTransactionRequest struct {

	NetworkIdentifier NetworkIdentifier `json:"network_identifier"`

	BlockIdentifier BlockIdentifier `json:"block_identifier"`

	TransactionIdentifier TransactionIdentifier `json:"transaction_identifier"`
}

// AssertBlockTransactionRequestRequired checks if the required fields are not zero-ed
func AssertBlockTransactionRequestRequired(obj BlockTransactionRequest) error {
	elements := map[string]interface{}{
		"network_identifier": obj.NetworkIdentifier,
		"block_identifier": obj.BlockIdentifier,
		"transaction_identifier": obj.TransactionIdentifier,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertNetworkIdentifierRequired(obj.NetworkIdentifier); err != nil {
		return err
	}
	if err := AssertBlockIdentifierRequired(obj.BlockIdentifier); err != nil {
		return err
	}
	if err := AssertTransactionIdentifierRequired(obj.TransactionIdentifier); err != nil {
		return err
	}
	return nil
}

// AssertBlockTransactionRequestConstraints checks if the values respects the defined constraints
func AssertBlockTransactionRequestConstraints(obj BlockTransactionRequest) error {
	if err := AssertNetworkIdentifierConstraints(obj.NetworkIdentifier); err != nil {
		return err
	}
	if err := AssertBlockIdentifierConstraints(obj.BlockIdentifier); err != nil {
		return err
	}
	if err := AssertTransactionIdentifierConstraints(obj.TransactionIdentifier); err != nil {
		return err
	}
	return nil
}
