// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// Signature - Signature contains the payload that was signed, the public keys of the keypairs used to produce the signature, the signature (encoded in hex), and the SignatureType. PublicKey is often times not known during construction of the signing payloads but may be needed to combine signatures properly.
type Signature struct {

	SigningPayload SigningPayload `json:"signing_payload"`

	PublicKey PublicKey `json:"public_key"`

	SignatureType SignatureType `json:"signature_type"`

	HexBytes string `json:"hex_bytes"`
}

// AssertSignatureRequired checks if the required fields are not zero-ed
func AssertSignatureRequired(obj Signature) error {
	elements := map[string]interface{}{
		"signing_payload": obj.SigningPayload,
		"public_key": obj.PublicKey,
		"signature_type": obj.SignatureType,
		"hex_bytes": obj.HexBytes,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertSigningPayloadRequired(obj.SigningPayload); err != nil {
		return err
	}
	if err := AssertPublicKeyRequired(obj.PublicKey); err != nil {
		return err
	}
	return nil
}

// AssertSignatureConstraints checks if the values respects the defined constraints
func AssertSignatureConstraints(obj Signature) error {
	if err := AssertSigningPayloadConstraints(obj.SigningPayload); err != nil {
		return err
	}
	if err := AssertPublicKeyConstraints(obj.PublicKey); err != nil {
		return err
	}
	return nil
}
