// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// SubNetworkIdentifier - In blockchains with sharded state, the SubNetworkIdentifier is required to query some object on a specific shard. This identifier is optional for all non-sharded blockchains.
type SubNetworkIdentifier struct {

	Network string `json:"network"`

	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// AssertSubNetworkIdentifierRequired checks if the required fields are not zero-ed
func AssertSubNetworkIdentifierRequired(obj SubNetworkIdentifier) error {
	elements := map[string]interface{}{
		"network": obj.Network,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertSubNetworkIdentifierConstraints checks if the values respects the defined constraints
func AssertSubNetworkIdentifierConstraints(obj SubNetworkIdentifier) error {
	return nil
}
