// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// SubAccountIdentifier - An account may have state specific to a contract address (ERC-20 token) and/or a stake (delegated balance). The sub_account_identifier should specify which state (if applicable) an account instantiation refers to.
type SubAccountIdentifier struct {

	// The SubAccount address may be a cryptographic value or some other identifier (ex: bonded) that uniquely specifies a SubAccount.
	Address string `json:"address"`

	// If the SubAccount address is not sufficient to uniquely specify a SubAccount, any other identifying information can be stored here. It is important to note that two SubAccounts with identical addresses but differing metadata will not be considered equal by clients.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// AssertSubAccountIdentifierRequired checks if the required fields are not zero-ed
func AssertSubAccountIdentifierRequired(obj SubAccountIdentifier) error {
	elements := map[string]interface{}{
		"address": obj.Address,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertSubAccountIdentifierConstraints checks if the values respects the defined constraints
func AssertSubAccountIdentifierConstraints(obj SubAccountIdentifier) error {
	return nil
}
