// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi


import (
	"errors"
)



// SearchTransactionsResponse - SearchTransactionsResponse contains an ordered collection of BlockTransactions that match the query in SearchTransactionsRequest. These BlockTransactions are sorted from most recent block to oldest block.
type SearchTransactionsResponse struct {

	// transactions is an array of BlockTransactions sorted by most recent BlockIdentifier (meaning that transactions in recent blocks appear first). If there are many transactions for a particular search, transactions may not contain all matching transactions. It is up to the caller to paginate these transactions using the max_block field.
	Transactions []BlockTransaction `json:"transactions"`

	// total_count is the number of results for a given search. Callers typically use this value to concurrently fetch results by offset or to display a virtual page number associated with results.
	TotalCount int64 `json:"total_count"`

	// next_offset is the next offset to use when paginating through transaction results. If this field is not populated, there are no more transactions to query.
	NextOffset int64 `json:"next_offset,omitempty"`
}

// AssertSearchTransactionsResponseRequired checks if the required fields are not zero-ed
func AssertSearchTransactionsResponseRequired(obj SearchTransactionsResponse) error {
	elements := map[string]interface{}{
		"transactions": obj.Transactions,
		"total_count": obj.TotalCount,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Transactions {
		if err := AssertBlockTransactionRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertSearchTransactionsResponseConstraints checks if the values respects the defined constraints
func AssertSearchTransactionsResponseConstraints(obj SearchTransactionsResponse) error {
	for _, el := range obj.Transactions {
		if err := AssertBlockTransactionConstraints(el); err != nil {
			return err
		}
	}
	if obj.TotalCount < 0 {
		return &ParsingError{Param: "TotalCount", Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.NextOffset < 0 {
		return &ParsingError{Param: "NextOffset", Err: errors.New(errMsgMinValueConstraint)}
	}
	return nil
}
