// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// SigningPayload - SigningPayload is signed by the client with the keypair associated with an AccountIdentifier using the specified SignatureType. SignatureType can be optionally populated if there is a restriction on the signature scheme that can be used to sign the payload.
type SigningPayload struct {

	// [DEPRECATED by `account_identifier` in `v1.4.4`] The network-specific address of the account that should sign the payload.
	Address string `json:"address,omitempty"`

	AccountIdentifier AccountIdentifier `json:"account_identifier,omitempty"`

	// Hex-encoded string of the payload bytes.
	HexBytes string `json:"hex_bytes"`

	SignatureType SignatureType `json:"signature_type,omitempty"`
}

// AssertSigningPayloadRequired checks if the required fields are not zero-ed
func AssertSigningPayloadRequired(obj SigningPayload) error {
	elements := map[string]interface{}{
		"hex_bytes": obj.HexBytes,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertAccountIdentifierRequired(obj.AccountIdentifier); err != nil {
		return err
	}
	return nil
}

// AssertSigningPayloadConstraints checks if the values respects the defined constraints
func AssertSigningPayloadConstraints(obj SigningPayload) error {
	if err := AssertAccountIdentifierConstraints(obj.AccountIdentifier); err != nil {
		return err
	}
	return nil
}
