// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// ConstructionParseResponse - ConstructionParseResponse contains an array of operations that occur in a transaction blob. This should match the array of operations provided to `/construction/preprocess` and `/construction/payloads`.
type ConstructionParseResponse struct {

	Operations []Operation `json:"operations"`

	// [DEPRECATED by `account_identifier_signers` in `v1.4.4`] All signers (addresses) of a particular transaction. If the transaction is unsigned, it should be empty.
	Signers []string `json:"signers,omitempty"`

	AccountIdentifierSigners []AccountIdentifier `json:"account_identifier_signers,omitempty"`

	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// AssertConstructionParseResponseRequired checks if the required fields are not zero-ed
func AssertConstructionParseResponseRequired(obj ConstructionParseResponse) error {
	elements := map[string]interface{}{
		"operations": obj.Operations,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Operations {
		if err := AssertOperationRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.AccountIdentifierSigners {
		if err := AssertAccountIdentifierRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertConstructionParseResponseConstraints checks if the values respects the defined constraints
func AssertConstructionParseResponseConstraints(obj ConstructionParseResponse) error {
	for _, el := range obj.Operations {
		if err := AssertOperationConstraints(el); err != nil {
			return err
		}
	}
	for _, el := range obj.AccountIdentifierSigners {
		if err := AssertAccountIdentifierConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
