// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// NetworkIdentifier - The network_identifier specifies which network a particular object is associated with.
type NetworkIdentifier struct {

	Blockchain string `json:"blockchain"`

	// If a blockchain has a specific chain-id or network identifier, it should go in this field. It is up to the client to determine which network-specific identifier is mainnet or testnet.
	Network string `json:"network"`

	SubNetworkIdentifier SubNetworkIdentifier `json:"sub_network_identifier,omitempty"`
}

// AssertNetworkIdentifierRequired checks if the required fields are not zero-ed
func AssertNetworkIdentifierRequired(obj NetworkIdentifier) error {
	elements := map[string]interface{}{
		"blockchain": obj.Blockchain,
		"network": obj.Network,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertSubNetworkIdentifierRequired(obj.SubNetworkIdentifier); err != nil {
		return err
	}
	return nil
}

// AssertNetworkIdentifierConstraints checks if the values respects the defined constraints
func AssertNetworkIdentifierConstraints(obj NetworkIdentifier) error {
	if err := AssertSubNetworkIdentifierConstraints(obj.SubNetworkIdentifier); err != nil {
		return err
	}
	return nil
}
