// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi


import (
	"fmt"
)


// Operator : Operator is used by query-related endpoints to determine how to apply conditions. If this field is not populated, the default `and` value will be used.
type Operator string

// List of Operator
const (
	OR Operator = "or"
	AND Operator = "and"
)

// AllowedOperatorEnumValues is all the allowed values of Operator enum
var AllowedOperatorEnumValues = []Operator{
	"or",
	"and",
}

// validOperatorEnumValue provides a map of Operators for fast verification of use input
var validOperatorEnumValues = map[Operator]struct{}{
	"or": {},
	"and": {},
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Operator) IsValid() bool {
	_, ok := validOperatorEnumValues[v]
	return ok
}

// NewOperatorFromValue returns a pointer to a valid Operator
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOperatorFromValue(v string) (Operator, error) {
	ev := Operator(v)
	if ev.IsValid() {
		return ev, nil
	}

	return "", fmt.Errorf("invalid value '%v' for Operator: valid values are %v", v, AllowedOperatorEnumValues)
}



// AssertOperatorRequired checks if the required fields are not zero-ed
func AssertOperatorRequired(obj Operator) error {
	return nil
}

// AssertOperatorConstraints checks if the values respects the defined constraints
func AssertOperatorConstraints(obj Operator) error {
	return nil
}
