// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// PartialBlockIdentifier - When fetching data by BlockIdentifier, it may be possible to only specify the index or hash. If neither property is specified, it is assumed that the client is making a request at the current block.
type PartialBlockIdentifier struct {

	Index int64 `json:"index,omitempty"`

	Hash string `json:"hash,omitempty"`
}

// AssertPartialBlockIdentifierRequired checks if the required fields are not zero-ed
func AssertPartialBlockIdentifierRequired(obj PartialBlockIdentifier) error {
	return nil
}

// AssertPartialBlockIdentifierConstraints checks if the values respects the defined constraints
func AssertPartialBlockIdentifierConstraints(obj PartialBlockIdentifier) error {
	return nil
}
