// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// BalanceExemption - BalanceExemption indicates that the balance for an exempt account could change without a corresponding Operation. This typically occurs with staking rewards, vesting balances, and Currencies with a dynamic supply. Currently, it is possible to exempt an account from strict reconciliation by SubAccountIdentifier.Address or by Currency. This means that any account with SubAccountIdentifier.Address would be exempt or any balance of a particular Currency would be exempt, respectively. BalanceExemptions should be used sparingly as they may introduce significant complexity for integrators that attempt to reconcile all account balance changes. If your implementation relies on any BalanceExemptions, you MUST implement historical balance lookup (the ability to query an account balance at any BlockIdentifier).
type BalanceExemption struct {

	// SubAccountAddress is the SubAccountIdentifier.Address that the BalanceExemption applies to (regardless of the value of SubAccountIdentifier.Metadata).
	SubAccountAddress string `json:"sub_account_address,omitempty"`

	Currency Currency `json:"currency,omitempty"`

	ExemptionType ExemptionType `json:"exemption_type,omitempty"`
}

// AssertBalanceExemptionRequired checks if the required fields are not zero-ed
func AssertBalanceExemptionRequired(obj BalanceExemption) error {
	if err := AssertCurrencyRequired(obj.Currency); err != nil {
		return err
	}
	return nil
}

// AssertBalanceExemptionConstraints checks if the values respects the defined constraints
func AssertBalanceExemptionConstraints(obj BalanceExemption) error {
	if err := AssertCurrencyConstraints(obj.Currency); err != nil {
		return err
	}
	return nil
}
