// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// MempoolTransactionRequest - A MempoolTransactionRequest is utilized to retrieve a transaction from the mempool.
type MempoolTransactionRequest struct {

	NetworkIdentifier NetworkIdentifier `json:"network_identifier"`

	TransactionIdentifier TransactionIdentifier `json:"transaction_identifier"`
}

// AssertMempoolTransactionRequestRequired checks if the required fields are not zero-ed
func AssertMempoolTransactionRequestRequired(obj MempoolTransactionRequest) error {
	elements := map[string]interface{}{
		"network_identifier": obj.NetworkIdentifier,
		"transaction_identifier": obj.TransactionIdentifier,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertNetworkIdentifierRequired(obj.NetworkIdentifier); err != nil {
		return err
	}
	if err := AssertTransactionIdentifierRequired(obj.TransactionIdentifier); err != nil {
		return err
	}
	return nil
}

// AssertMempoolTransactionRequestConstraints checks if the values respects the defined constraints
func AssertMempoolTransactionRequestConstraints(obj MempoolTransactionRequest) error {
	if err := AssertNetworkIdentifierConstraints(obj.NetworkIdentifier); err != nil {
		return err
	}
	if err := AssertTransactionIdentifierConstraints(obj.TransactionIdentifier); err != nil {
		return err
	}
	return nil
}
