// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi


import (
	"fmt"
)


// Case : Case specifies the expected case for strings and hashes.
type Case string

// List of Case
const (
	UPPER_CASE Case = "upper_case"
	LOWER_CASE Case = "lower_case"
	CASE_SENSITIVE Case = "case_sensitive"
)

// AllowedCaseEnumValues is all the allowed values of Case enum
var AllowedCaseEnumValues = []Case{
	"upper_case",
	"lower_case",
	"case_sensitive",
}

// validCaseEnumValue provides a map of Cases for fast verification of use input
var validCaseEnumValues = map[Case]struct{}{
	"upper_case": {},
	"lower_case": {},
	"case_sensitive": {},
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Case) IsValid() bool {
	_, ok := validCaseEnumValues[v]
	return ok
}

// NewCaseFromValue returns a pointer to a valid Case
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCaseFromValue(v string) (Case, error) {
	ev := Case(v)
	if ev.IsValid() {
		return ev, nil
	}

	return "", fmt.Errorf("invalid value '%v' for Case: valid values are %v", v, AllowedCaseEnumValues)
}



// AssertCaseRequired checks if the required fields are not zero-ed
func AssertCaseRequired(obj Case) error {
	return nil
}

// AssertCaseConstraints checks if the values respects the defined constraints
func AssertCaseConstraints(obj Case) error {
	return nil
}
