// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi


import (
	"errors"
)



// BlockEvent - BlockEvent represents the addition or removal of a BlockIdentifier from storage. Streaming BlockEvents allows lightweight clients to update their own state without needing to implement their own syncing logic.
type BlockEvent struct {

	// sequence is the unique identifier of a BlockEvent within the context of a NetworkIdentifier.
	Sequence int64 `json:"sequence"`

	BlockIdentifier BlockIdentifier `json:"block_identifier"`

	Type BlockEventType `json:"type"`
}

// AssertBlockEventRequired checks if the required fields are not zero-ed
func AssertBlockEventRequired(obj BlockEvent) error {
	elements := map[string]interface{}{
		"sequence": obj.Sequence,
		"block_identifier": obj.BlockIdentifier,
		"type": obj.Type,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertBlockIdentifierRequired(obj.BlockIdentifier); err != nil {
		return err
	}
	return nil
}

// AssertBlockEventConstraints checks if the values respects the defined constraints
func AssertBlockEventConstraints(obj BlockEvent) error {
	if obj.Sequence < 0 {
		return &ParsingError{Param: "Sequence", Err: errors.New(errMsgMinValueConstraint)}
	}
	if err := AssertBlockIdentifierConstraints(obj.BlockIdentifier); err != nil {
		return err
	}
	return nil
}
