// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// BlockTransaction - BlockTransaction contains a populated Transaction and the BlockIdentifier that contains it.
type BlockTransaction struct {

	BlockIdentifier BlockIdentifier `json:"block_identifier"`

	Transaction Transaction `json:"transaction"`
}

// AssertBlockTransactionRequired checks if the required fields are not zero-ed
func AssertBlockTransactionRequired(obj BlockTransaction) error {
	elements := map[string]interface{}{
		"block_identifier": obj.BlockIdentifier,
		"transaction": obj.Transaction,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertBlockIdentifierRequired(obj.BlockIdentifier); err != nil {
		return err
	}
	if err := AssertTransactionRequired(obj.Transaction); err != nil {
		return err
	}
	return nil
}

// AssertBlockTransactionConstraints checks if the values respects the defined constraints
func AssertBlockTransactionConstraints(obj BlockTransaction) error {
	if err := AssertBlockIdentifierConstraints(obj.BlockIdentifier); err != nil {
		return err
	}
	if err := AssertTransactionConstraints(obj.Transaction); err != nil {
		return err
	}
	return nil
}
