// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// ConstructionPayloadsResponse - ConstructionTransactionResponse is returned by `/construction/payloads`. It contains an unsigned transaction blob (that is usually needed to construct the a network transaction from a collection of signatures) and an array of payloads that must be signed by the caller.
type ConstructionPayloadsResponse struct {

	UnsignedTransaction string `json:"unsigned_transaction"`

	Payloads []SigningPayload `json:"payloads"`
}

// AssertConstructionPayloadsResponseRequired checks if the required fields are not zero-ed
func AssertConstructionPayloadsResponseRequired(obj ConstructionPayloadsResponse) error {
	elements := map[string]interface{}{
		"unsigned_transaction": obj.UnsignedTransaction,
		"payloads": obj.Payloads,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Payloads {
		if err := AssertSigningPayloadRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertConstructionPayloadsResponseConstraints checks if the values respects the defined constraints
func AssertConstructionPayloadsResponseConstraints(obj ConstructionPayloadsResponse) error {
	for _, el := range obj.Payloads {
		if err := AssertSigningPayloadConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
