// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// ConstructionMetadataRequest - A ConstructionMetadataRequest is utilized to get information required to construct a transaction. The Options object used to specify which metadata to return is left purposely unstructured to allow flexibility for implementers. Options is not required in the case that there is network-wide metadata of interest. Optionally, the request can also include an array of PublicKeys associated with the AccountIdentifiers returned in ConstructionPreprocessResponse.
type ConstructionMetadataRequest struct {

	NetworkIdentifier NetworkIdentifier `json:"network_identifier"`

	// Some blockchains require different metadata for different types of transaction construction (ex: delegation versus a transfer). Instead of requiring a blockchain node to return all possible types of metadata for construction (which may require multiple node fetches), the client can populate an options object to limit the metadata returned to only the subset required.
	Options map[string]interface{} `json:"options,omitempty"`

	PublicKeys []PublicKey `json:"public_keys,omitempty"`
}

// AssertConstructionMetadataRequestRequired checks if the required fields are not zero-ed
func AssertConstructionMetadataRequestRequired(obj ConstructionMetadataRequest) error {
	elements := map[string]interface{}{
		"network_identifier": obj.NetworkIdentifier,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertNetworkIdentifierRequired(obj.NetworkIdentifier); err != nil {
		return err
	}
	for _, el := range obj.PublicKeys {
		if err := AssertPublicKeyRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertConstructionMetadataRequestConstraints checks if the values respects the defined constraints
func AssertConstructionMetadataRequestConstraints(obj ConstructionMetadataRequest) error {
	if err := AssertNetworkIdentifierConstraints(obj.NetworkIdentifier); err != nil {
		return err
	}
	for _, el := range obj.PublicKeys {
		if err := AssertPublicKeyConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
