// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// OperationStatus - OperationStatus is utilized to indicate which Operation status are considered successful.
type OperationStatus struct {

	// The status is the network-specific status of the operation.
	Status string `json:"status"`

	// An Operation is considered successful if the Operation.Amount should affect the Operation.Account. Some blockchains (like Bitcoin) only include successful operations in blocks but other blockchains (like Ethereum) include unsuccessful operations that incur a fee. To reconcile the computed balance from the stream of Operations, it is critical to understand which Operation.Status indicate an Operation is successful and should affect an Account.
	Successful bool `json:"successful"`
}

// AssertOperationStatusRequired checks if the required fields are not zero-ed
func AssertOperationStatusRequired(obj OperationStatus) error {
	elements := map[string]interface{}{
		"status": obj.Status,
		"successful": obj.Successful,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertOperationStatusConstraints checks if the values respects the defined constraints
func AssertOperationStatusConstraints(obj OperationStatus) error {
	return nil
}
