// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// Coin - Coin contains its unique identifier and the amount it represents.
type Coin struct {

	CoinIdentifier CoinIdentifier `json:"coin_identifier"`

	Amount Amount `json:"amount"`
}

// AssertCoinRequired checks if the required fields are not zero-ed
func AssertCoinRequired(obj Coin) error {
	elements := map[string]interface{}{
		"coin_identifier": obj.CoinIdentifier,
		"amount": obj.Amount,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertCoinIdentifierRequired(obj.CoinIdentifier); err != nil {
		return err
	}
	if err := AssertAmountRequired(obj.Amount); err != nil {
		return err
	}
	return nil
}

// AssertCoinConstraints checks if the values respects the defined constraints
func AssertCoinConstraints(obj Coin) error {
	if err := AssertCoinIdentifierConstraints(obj.CoinIdentifier); err != nil {
		return err
	}
	if err := AssertAmountConstraints(obj.Amount); err != nil {
		return err
	}
	return nil
}
