// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// PublicKey - PublicKey contains a public key byte array for a particular CurveType encoded in hex. Note that there is no PrivateKey struct as this is NEVER the concern of an implementation.
type PublicKey struct {

	// Hex-encoded public key bytes in the format specified by the CurveType.
	HexBytes string `json:"hex_bytes"`

	CurveType CurveType `json:"curve_type"`
}

// AssertPublicKeyRequired checks if the required fields are not zero-ed
func AssertPublicKeyRequired(obj PublicKey) error {
	elements := map[string]interface{}{
		"hex_bytes": obj.HexBytes,
		"curve_type": obj.CurveType,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertPublicKeyConstraints checks if the values respects the defined constraints
func AssertPublicKeyConstraints(obj PublicKey) error {
	return nil
}
