// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// AccountCoinsRequest - AccountCoinsRequest is utilized to make a request on the /account/coins endpoint.
type AccountCoinsRequest struct {

	NetworkIdentifier NetworkIdentifier `json:"network_identifier"`

	AccountIdentifier AccountIdentifier `json:"account_identifier"`

	// Include state from the mempool when looking up an account's unspent coins. Note, using this functionality breaks any guarantee of idempotency.
	IncludeMempool bool `json:"include_mempool"`

	// In some cases, the caller may not want to retrieve coins for all currencies for an AccountIdentifier. If the currencies field is populated, only coins for the specified currencies will be returned. If not populated, all unspent coins will be returned.
	Currencies []Currency `json:"currencies,omitempty"`
}

// AssertAccountCoinsRequestRequired checks if the required fields are not zero-ed
func AssertAccountCoinsRequestRequired(obj AccountCoinsRequest) error {
	elements := map[string]interface{}{
		"network_identifier": obj.NetworkIdentifier,
		"account_identifier": obj.AccountIdentifier,
		"include_mempool": obj.IncludeMempool,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertNetworkIdentifierRequired(obj.NetworkIdentifier); err != nil {
		return err
	}
	if err := AssertAccountIdentifierRequired(obj.AccountIdentifier); err != nil {
		return err
	}
	for _, el := range obj.Currencies {
		if err := AssertCurrencyRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertAccountCoinsRequestConstraints checks if the values respects the defined constraints
func AssertAccountCoinsRequestConstraints(obj AccountCoinsRequest) error {
	if err := AssertNetworkIdentifierConstraints(obj.NetworkIdentifier); err != nil {
		return err
	}
	if err := AssertAccountIdentifierConstraints(obj.AccountIdentifier); err != nil {
		return err
	}
	for _, el := range obj.Currencies {
		if err := AssertCurrencyConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
