// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// MempoolTransactionResponse - A MempoolTransactionResponse contains an estimate of a mempool transaction. It may not be possible to know the full impact of a transaction in the mempool (ex: fee paid).
type MempoolTransactionResponse struct {

	Transaction Transaction `json:"transaction"`

	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// AssertMempoolTransactionResponseRequired checks if the required fields are not zero-ed
func AssertMempoolTransactionResponseRequired(obj MempoolTransactionResponse) error {
	elements := map[string]interface{}{
		"transaction": obj.Transaction,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertTransactionRequired(obj.Transaction); err != nil {
		return err
	}
	return nil
}

// AssertMempoolTransactionResponseConstraints checks if the values respects the defined constraints
func AssertMempoolTransactionResponseConstraints(obj MempoolTransactionResponse) error {
	if err := AssertTransactionConstraints(obj.Transaction); err != nil {
		return err
	}
	return nil
}
