// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// Version - The Version object is utilized to inform the client of the versions of different components of the Rosetta implementation.
type Version struct {

	// The rosetta_version is the version of the Rosetta interface the implementation adheres to. This can be useful for clients looking to reliably parse responses.
	RosettaVersion string `json:"rosetta_version"`

	// The node_version is the canonical version of the node runtime. This can help clients manage deployments.
	NodeVersion string `json:"node_version"`

	// When a middleware server is used to adhere to the Rosetta interface, it should return its version here. This can help clients manage deployments.
	MiddlewareVersion string `json:"middleware_version,omitempty"`

	// Any other information that may be useful about versioning of dependent services should be returned here.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// AssertVersionRequired checks if the required fields are not zero-ed
func AssertVersionRequired(obj Version) error {
	elements := map[string]interface{}{
		"rosetta_version": obj.RosettaVersion,
		"node_version": obj.NodeVersion,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertVersionConstraints checks if the values respects the defined constraints
func AssertVersionConstraints(obj Version) error {
	return nil
}
