// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// RelatedTransaction - The related_transaction allows implementations to link together multiple transactions. An unpopulated network identifier indicates that the related transaction is on the same network.
type RelatedTransaction struct {

	NetworkIdentifier NetworkIdentifier `json:"network_identifier,omitempty"`

	TransactionIdentifier TransactionIdentifier `json:"transaction_identifier"`

	Direction Direction `json:"direction"`
}

// AssertRelatedTransactionRequired checks if the required fields are not zero-ed
func AssertRelatedTransactionRequired(obj RelatedTransaction) error {
	elements := map[string]interface{}{
		"transaction_identifier": obj.TransactionIdentifier,
		"direction": obj.Direction,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertNetworkIdentifierRequired(obj.NetworkIdentifier); err != nil {
		return err
	}
	if err := AssertTransactionIdentifierRequired(obj.TransactionIdentifier); err != nil {
		return err
	}
	return nil
}

// AssertRelatedTransactionConstraints checks if the values respects the defined constraints
func AssertRelatedTransactionConstraints(obj RelatedTransaction) error {
	if err := AssertNetworkIdentifierConstraints(obj.NetworkIdentifier); err != nil {
		return err
	}
	if err := AssertTransactionIdentifierConstraints(obj.TransactionIdentifier); err != nil {
		return err
	}
	return nil
}
