// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// NetworkRequest - A NetworkRequest is utilized to retrieve some data specific exclusively to a NetworkIdentifier.
type NetworkRequest struct {

	NetworkIdentifier NetworkIdentifier `json:"network_identifier"`

	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// AssertNetworkRequestRequired checks if the required fields are not zero-ed
func AssertNetworkRequestRequired(obj NetworkRequest) error {
	elements := map[string]interface{}{
		"network_identifier": obj.NetworkIdentifier,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertNetworkIdentifierRequired(obj.NetworkIdentifier); err != nil {
		return err
	}
	return nil
}

// AssertNetworkRequestConstraints checks if the values respects the defined constraints
func AssertNetworkRequestConstraints(obj NetworkRequest) error {
	if err := AssertNetworkIdentifierConstraints(obj.NetworkIdentifier); err != nil {
		return err
	}
	return nil
}
