// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// MempoolResponse - A MempoolResponse contains all transaction identifiers in the mempool for a particular network_identifier.
type MempoolResponse struct {

	TransactionIdentifiers []TransactionIdentifier `json:"transaction_identifiers"`
}

// AssertMempoolResponseRequired checks if the required fields are not zero-ed
func AssertMempoolResponseRequired(obj MempoolResponse) error {
	elements := map[string]interface{}{
		"transaction_identifiers": obj.TransactionIdentifiers,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.TransactionIdentifiers {
		if err := AssertTransactionIdentifierRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertMempoolResponseConstraints checks if the values respects the defined constraints
func AssertMempoolResponseConstraints(obj MempoolResponse) error {
	for _, el := range obj.TransactionIdentifiers {
		if err := AssertTransactionIdentifierConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
