// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// CoinChange - CoinChange is used to represent a change in state of a some coin identified by a coin_identifier. This object is part of the Operation model and must be populated for UTXO-based blockchains. Coincidentally, this abstraction of UTXOs allows for supporting both account-based transfers and UTXO-based transfers on the same blockchain (when a transfer is account-based, don't populate this model).
type CoinChange struct {

	CoinIdentifier CoinIdentifier `json:"coin_identifier"`

	CoinAction CoinAction `json:"coin_action"`
}

// AssertCoinChangeRequired checks if the required fields are not zero-ed
func AssertCoinChangeRequired(obj CoinChange) error {
	elements := map[string]interface{}{
		"coin_identifier": obj.CoinIdentifier,
		"coin_action": obj.CoinAction,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertCoinIdentifierRequired(obj.CoinIdentifier); err != nil {
		return err
	}
	return nil
}

// AssertCoinChangeConstraints checks if the values respects the defined constraints
func AssertCoinChangeConstraints(obj CoinChange) error {
	if err := AssertCoinIdentifierConstraints(obj.CoinIdentifier); err != nil {
		return err
	}
	return nil
}
