// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// ConstructionCombineRequest - ConstructionCombineRequest is the input to the `/construction/combine` endpoint. It contains the unsigned transaction blob returned by `/construction/payloads` and all required signatures to create a network transaction.
type ConstructionCombineRequest struct {

	NetworkIdentifier NetworkIdentifier `json:"network_identifier"`

	UnsignedTransaction string `json:"unsigned_transaction"`

	Signatures []Signature `json:"signatures"`
}

// AssertConstructionCombineRequestRequired checks if the required fields are not zero-ed
func AssertConstructionCombineRequestRequired(obj ConstructionCombineRequest) error {
	elements := map[string]interface{}{
		"network_identifier": obj.NetworkIdentifier,
		"unsigned_transaction": obj.UnsignedTransaction,
		"signatures": obj.Signatures,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertNetworkIdentifierRequired(obj.NetworkIdentifier); err != nil {
		return err
	}
	for _, el := range obj.Signatures {
		if err := AssertSignatureRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertConstructionCombineRequestConstraints checks if the values respects the defined constraints
func AssertConstructionCombineRequestConstraints(obj ConstructionCombineRequest) error {
	if err := AssertNetworkIdentifierConstraints(obj.NetworkIdentifier); err != nil {
		return err
	}
	for _, el := range obj.Signatures {
		if err := AssertSignatureConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
