// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// ConstructionPayloadsRequest - ConstructionPayloadsRequest is the request to `/construction/payloads`. It contains the network, a slice of operations, and arbitrary metadata that was returned by the call to `/construction/metadata`. Optionally, the request can also include an array of PublicKeys associated with the AccountIdentifiers returned in ConstructionPreprocessResponse.
type ConstructionPayloadsRequest struct {

	NetworkIdentifier NetworkIdentifier `json:"network_identifier"`

	Operations []Operation `json:"operations"`

	Metadata map[string]interface{} `json:"metadata,omitempty"`

	PublicKeys []PublicKey `json:"public_keys,omitempty"`
}

// AssertConstructionPayloadsRequestRequired checks if the required fields are not zero-ed
func AssertConstructionPayloadsRequestRequired(obj ConstructionPayloadsRequest) error {
	elements := map[string]interface{}{
		"network_identifier": obj.NetworkIdentifier,
		"operations": obj.Operations,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertNetworkIdentifierRequired(obj.NetworkIdentifier); err != nil {
		return err
	}
	for _, el := range obj.Operations {
		if err := AssertOperationRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.PublicKeys {
		if err := AssertPublicKeyRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertConstructionPayloadsRequestConstraints checks if the values respects the defined constraints
func AssertConstructionPayloadsRequestConstraints(obj ConstructionPayloadsRequest) error {
	if err := AssertNetworkIdentifierConstraints(obj.NetworkIdentifier); err != nil {
		return err
	}
	for _, el := range obj.Operations {
		if err := AssertOperationConstraints(el); err != nil {
			return err
		}
	}
	for _, el := range obj.PublicKeys {
		if err := AssertPublicKeyConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
