// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi


import (
	"errors"
)



// Currency - Currency is composed of a canonical Symbol and Decimals. This Decimals value is used to convert an Amount.Value from atomic units (Satoshis) to standard units (Bitcoins).
type Currency struct {

	// Canonical symbol associated with a currency.
	Symbol string `json:"symbol"`

	// Number of decimal places in the standard unit representation of the amount. For example, BTC has 8 decimals. Note that it is not possible to represent the value of some currency in atomic units that is not base 10.
	Decimals int32 `json:"decimals"`

	// Any additional information related to the currency itself. For example, it would be useful to populate this object with the contract address of an ERC-20 token.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// AssertCurrencyRequired checks if the required fields are not zero-ed
func AssertCurrencyRequired(obj Currency) error {
	elements := map[string]interface{}{
		"symbol": obj.Symbol,
		"decimals": obj.Decimals,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCurrencyConstraints checks if the values respects the defined constraints
func AssertCurrencyConstraints(obj Currency) error {
	if obj.Decimals < 0 {
		return &ParsingError{Param: "Decimals", Err: errors.New(errMsgMinValueConstraint)}
	}
	return nil
}
