// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// CallResponse - CallResponse contains the result of a `/call` invocation.
type CallResponse struct {

	// Result contains the result of the `/call` invocation. This result will not be inspected or interpreted by Rosetta tooling and is left to the caller to decode.
	Result map[string]interface{} `json:"result"`

	// Idempotent indicates that if `/call` is invoked with the same CallRequest again, at any point in time, it will return the same CallResponse. Integrators may cache the CallResponse if this is set to true to avoid making unnecessary calls to the Rosetta implementation. For this reason, implementers should be very conservative about returning true here or they could cause issues for the caller.
	Idempotent bool `json:"idempotent"`
}

// AssertCallResponseRequired checks if the required fields are not zero-ed
func AssertCallResponseRequired(obj CallResponse) error {
	elements := map[string]interface{}{
		"result": obj.Result,
		"idempotent": obj.Idempotent,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCallResponseConstraints checks if the values respects the defined constraints
func AssertCallResponseConstraints(obj CallResponse) error {
	return nil
}
