// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// AccountBalanceResponse - An AccountBalanceResponse is returned on the /account/balance endpoint. If an account has a balance for each AccountIdentifier describing it (ex: an ERC-20 token balance on a few smart contracts), an account balance request must be made with each AccountIdentifier. The `coins` field was removed and replaced by by `/account/coins` in `v1.4.7`.
type AccountBalanceResponse struct {

	BlockIdentifier BlockIdentifier `json:"block_identifier"`

	// A single account may have a balance in multiple currencies.
	Balances []Amount `json:"balances"`

	// Account-based blockchains that utilize a nonce or sequence number should include that number in the metadata. This number could be unique to the identifier or global across the account address.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// AssertAccountBalanceResponseRequired checks if the required fields are not zero-ed
func AssertAccountBalanceResponseRequired(obj AccountBalanceResponse) error {
	elements := map[string]interface{}{
		"block_identifier": obj.BlockIdentifier,
		"balances": obj.Balances,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertBlockIdentifierRequired(obj.BlockIdentifier); err != nil {
		return err
	}
	for _, el := range obj.Balances {
		if err := AssertAmountRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertAccountBalanceResponseConstraints checks if the values respects the defined constraints
func AssertAccountBalanceResponseConstraints(obj AccountBalanceResponse) error {
	if err := AssertBlockIdentifierConstraints(obj.BlockIdentifier); err != nil {
		return err
	}
	for _, el := range obj.Balances {
		if err := AssertAmountConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
