// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// ConstructionMetadataResponse - The ConstructionMetadataResponse returns network-specific metadata used for transaction construction. Optionally, the implementer can return the suggested fee associated with the transaction being constructed. The caller may use this info to adjust the intent of the transaction or to create a transaction with a different account that can pay the suggested fee. Suggested fee is an array in case fee payment must occur in multiple currencies.
type ConstructionMetadataResponse struct {

	Metadata map[string]interface{} `json:"metadata"`

	SuggestedFee []Amount `json:"suggested_fee,omitempty"`
}

// AssertConstructionMetadataResponseRequired checks if the required fields are not zero-ed
func AssertConstructionMetadataResponseRequired(obj ConstructionMetadataResponse) error {
	elements := map[string]interface{}{
		"metadata": obj.Metadata,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.SuggestedFee {
		if err := AssertAmountRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertConstructionMetadataResponseConstraints checks if the values respects the defined constraints
func AssertConstructionMetadataResponseConstraints(obj ConstructionMetadataResponse) error {
	for _, el := range obj.SuggestedFee {
		if err := AssertAmountConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
