// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi


import (
	"fmt"
)


// CurveType : CurveType is the type of cryptographic curve associated with a PublicKey. * secp256k1: SEC compressed - `33 bytes` (https://secg.org/sec1-v2.pdf#subsubsection.2.3.3) * secp256k1_bip340: x-only - `32 bytes`  (implicitly even `Y` coord. Secp256k1 compressed keys may be repurposed by dropping the first byte. (https://github.com/bitcoin/bips/blob/master/bip-0340.mediawiki#Public_Key_Generation)) * secp256r1: SEC compressed - `33 bytes` (https://secg.org/sec1-v2.pdf#subsubsection.2.3.3) * edwards25519: `y (255-bits) || x-sign-bit (1-bit)` - `32 bytes` (https://ed25519.cr.yp.to/ed25519-20110926.pdf) * tweedle: 1st pk : Fq.t (32 bytes) || 2nd pk : Fq.t (32 bytes) (https://github.com/CodaProtocol/coda/blob/develop/rfcs/0038-rosetta-construction-api.md#marshal-keys) * pallas: `x (255 bits) || y-parity-bit (1-bit) - 32 bytes` (https://github.com/zcash/pasta)
type CurveType string

// List of CurveType
const (
	SECP256K1 CurveType = "secp256k1"
	SECP256K1_BIP340 CurveType = "secp256k1_bip340"
	SECP256R1 CurveType = "secp256r1"
	EDWARDS25519 CurveType = "edwards25519"
	TWEEDLE CurveType = "tweedle"
	PALLAS CurveType = "pallas"
)

// AllowedCurveTypeEnumValues is all the allowed values of CurveType enum
var AllowedCurveTypeEnumValues = []CurveType{
	"secp256k1",
	"secp256k1_bip340",
	"secp256r1",
	"edwards25519",
	"tweedle",
	"pallas",
}

// validCurveTypeEnumValue provides a map of CurveTypes for fast verification of use input
var validCurveTypeEnumValues = map[CurveType]struct{}{
	"secp256k1": {},
	"secp256k1_bip340": {},
	"secp256r1": {},
	"edwards25519": {},
	"tweedle": {},
	"pallas": {},
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CurveType) IsValid() bool {
	_, ok := validCurveTypeEnumValues[v]
	return ok
}

// NewCurveTypeFromValue returns a pointer to a valid CurveType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCurveTypeFromValue(v string) (CurveType, error) {
	ev := CurveType(v)
	if ev.IsValid() {
		return ev, nil
	}

	return "", fmt.Errorf("invalid value '%v' for CurveType: valid values are %v", v, AllowedCurveTypeEnumValues)
}



// AssertCurveTypeRequired checks if the required fields are not zero-ed
func AssertCurveTypeRequired(obj CurveType) error {
	return nil
}

// AssertCurveTypeConstraints checks if the values respects the defined constraints
func AssertCurveTypeConstraints(obj CurveType) error {
	return nil
}
