// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi


import (
	"fmt"
)


// Direction : Used by RelatedTransaction to indicate the direction of the relation (i.e. cross-shard/cross-network sends may reference `backward` to an earlier transaction and async execution may reference `forward`). Can be used to indicate if a transaction relation is from child to parent or the reverse.
type Direction string

// List of Direction
const (
	FORWARD Direction = "forward"
	BACKWARD Direction = "backward"
)

// AllowedDirectionEnumValues is all the allowed values of Direction enum
var AllowedDirectionEnumValues = []Direction{
	"forward",
	"backward",
}

// validDirectionEnumValue provides a map of Directions for fast verification of use input
var validDirectionEnumValues = map[Direction]struct{}{
	"forward": {},
	"backward": {},
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Direction) IsValid() bool {
	_, ok := validDirectionEnumValues[v]
	return ok
}

// NewDirectionFromValue returns a pointer to a valid Direction
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDirectionFromValue(v string) (Direction, error) {
	ev := Direction(v)
	if ev.IsValid() {
		return ev, nil
	}

	return "", fmt.Errorf("invalid value '%v' for Direction: valid values are %v", v, AllowedDirectionEnumValues)
}



// AssertDirectionRequired checks if the required fields are not zero-ed
func AssertDirectionRequired(obj Direction) error {
	return nil
}

// AssertDirectionConstraints checks if the values respects the defined constraints
func AssertDirectionConstraints(obj Direction) error {
	return nil
}
