// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// BlockIdentifier - The block_identifier uniquely identifies a block in a particular network.
type BlockIdentifier struct {

	// This is also known as the block height.
	Index int64 `json:"index"`

	// This should be normalized according to the case specified in the block_hash_case network options.
	Hash string `json:"hash"`
}

// AssertBlockIdentifierRequired checks if the required fields are not zero-ed
func AssertBlockIdentifierRequired(obj BlockIdentifier) error {
	elements := map[string]interface{}{
		"index": obj.Index,
		"hash": obj.Hash,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertBlockIdentifierConstraints checks if the values respects the defined constraints
func AssertBlockIdentifierConstraints(obj BlockIdentifier) error {
	return nil
}
