// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// CoinIdentifier - CoinIdentifier uniquely identifies a Coin.
type CoinIdentifier struct {

	// Identifier should be populated with a globally unique identifier of a Coin. In Bitcoin, this identifier would be transaction_hash:index.
	Identifier string `json:"identifier"`
}

// AssertCoinIdentifierRequired checks if the required fields are not zero-ed
func AssertCoinIdentifierRequired(obj CoinIdentifier) error {
	elements := map[string]interface{}{
		"identifier": obj.Identifier,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCoinIdentifierConstraints checks if the values respects the defined constraints
func AssertCoinIdentifierConstraints(obj CoinIdentifier) error {
	return nil
}
