// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// NetworkOptionsResponse - NetworkOptionsResponse contains information about the versioning of the node and the allowed operation statuses, operation types, and errors.
type NetworkOptionsResponse struct {

	Version Version `json:"version"`

	Allow Allow `json:"allow"`
}

// AssertNetworkOptionsResponseRequired checks if the required fields are not zero-ed
func AssertNetworkOptionsResponseRequired(obj NetworkOptionsResponse) error {
	elements := map[string]interface{}{
		"version": obj.Version,
		"allow": obj.Allow,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertVersionRequired(obj.Version); err != nil {
		return err
	}
	if err := AssertAllowRequired(obj.Allow); err != nil {
		return err
	}
	return nil
}

// AssertNetworkOptionsResponseConstraints checks if the values respects the defined constraints
func AssertNetworkOptionsResponseConstraints(obj NetworkOptionsResponse) error {
	if err := AssertVersionConstraints(obj.Version); err != nil {
		return err
	}
	if err := AssertAllowConstraints(obj.Allow); err != nil {
		return err
	}
	return nil
}
