// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// BlockTransactionResponse - A BlockTransactionResponse contains information about a block transaction.
type BlockTransactionResponse struct {

	Transaction Transaction `json:"transaction"`
}

// AssertBlockTransactionResponseRequired checks if the required fields are not zero-ed
func AssertBlockTransactionResponseRequired(obj BlockTransactionResponse) error {
	elements := map[string]interface{}{
		"transaction": obj.Transaction,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertTransactionRequired(obj.Transaction); err != nil {
		return err
	}
	return nil
}

// AssertBlockTransactionResponseConstraints checks if the values respects the defined constraints
func AssertBlockTransactionResponseConstraints(obj BlockTransactionResponse) error {
	if err := AssertTransactionConstraints(obj.Transaction); err != nil {
		return err
	}
	return nil
}
