// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi


import (
	"fmt"
)


// ExemptionType : ExemptionType is used to indicate if the live balance for an account subject to a BalanceExemption could increase above, decrease below, or equal the computed balance. * greater_or_equal: The live balance may increase above or equal the computed balance. This typically   occurs with staking rewards that accrue on each block. * less_or_equal: The live balance may decrease below or equal the computed balance. This typically   occurs as balance moves from locked to spendable on a vesting account. * dynamic: The live balance may increase above, decrease below, or equal the computed balance. This   typically occurs with tokens that have a dynamic supply.
type ExemptionType string

// List of ExemptionType
const (
	GREATER_OR_EQUAL ExemptionType = "greater_or_equal"
	LESS_OR_EQUAL ExemptionType = "less_or_equal"
	DYNAMIC ExemptionType = "dynamic"
)

// AllowedExemptionTypeEnumValues is all the allowed values of ExemptionType enum
var AllowedExemptionTypeEnumValues = []ExemptionType{
	"greater_or_equal",
	"less_or_equal",
	"dynamic",
}

// validExemptionTypeEnumValue provides a map of ExemptionTypes for fast verification of use input
var validExemptionTypeEnumValues = map[ExemptionType]struct{}{
	"greater_or_equal": {},
	"less_or_equal": {},
	"dynamic": {},
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ExemptionType) IsValid() bool {
	_, ok := validExemptionTypeEnumValues[v]
	return ok
}

// NewExemptionTypeFromValue returns a pointer to a valid ExemptionType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewExemptionTypeFromValue(v string) (ExemptionType, error) {
	ev := ExemptionType(v)
	if ev.IsValid() {
		return ev, nil
	}

	return "", fmt.Errorf("invalid value '%v' for ExemptionType: valid values are %v", v, AllowedExemptionTypeEnumValues)
}



// AssertExemptionTypeRequired checks if the required fields are not zero-ed
func AssertExemptionTypeRequired(obj ExemptionType) error {
	return nil
}

// AssertExemptionTypeConstraints checks if the values respects the defined constraints
func AssertExemptionTypeConstraints(obj ExemptionType) error {
	return nil
}
