// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// TransactionIdentifierResponse - TransactionIdentifierResponse contains the transaction_identifier of a transaction that was submitted to either `/construction/hash` or `/construction/submit`.
type TransactionIdentifierResponse struct {

	TransactionIdentifier TransactionIdentifier `json:"transaction_identifier"`

	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// AssertTransactionIdentifierResponseRequired checks if the required fields are not zero-ed
func AssertTransactionIdentifierResponseRequired(obj TransactionIdentifierResponse) error {
	elements := map[string]interface{}{
		"transaction_identifier": obj.TransactionIdentifier,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertTransactionIdentifierRequired(obj.TransactionIdentifier); err != nil {
		return err
	}
	return nil
}

// AssertTransactionIdentifierResponseConstraints checks if the values respects the defined constraints
func AssertTransactionIdentifierResponseConstraints(obj TransactionIdentifierResponse) error {
	if err := AssertTransactionIdentifierConstraints(obj.TransactionIdentifier); err != nil {
		return err
	}
	return nil
}
