// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi


import (
	"errors"
)



// EventsBlocksResponse - EventsBlocksResponse contains an ordered collection of BlockEvents and the max retrievable sequence.
type EventsBlocksResponse struct {

	// max_sequence is the maximum available sequence number to fetch.
	MaxSequence int64 `json:"max_sequence"`

	// events is an array of BlockEvents indicating the order to add and remove blocks to maintain a canonical view of blockchain state. Lightweight clients can use this event stream to update state without implementing their own block syncing logic.
	Events []BlockEvent `json:"events"`
}

// AssertEventsBlocksResponseRequired checks if the required fields are not zero-ed
func AssertEventsBlocksResponseRequired(obj EventsBlocksResponse) error {
	elements := map[string]interface{}{
		"max_sequence": obj.MaxSequence,
		"events": obj.Events,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Events {
		if err := AssertBlockEventRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertEventsBlocksResponseConstraints checks if the values respects the defined constraints
func AssertEventsBlocksResponseConstraints(obj EventsBlocksResponse) error {
	if obj.MaxSequence < 0 {
		return &ParsingError{Param: "MaxSequence", Err: errors.New(errMsgMinValueConstraint)}
	}
	for _, el := range obj.Events {
		if err := AssertBlockEventConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
