// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// ConstructionSubmitRequest - The transaction submission request includes a signed transaction.
type ConstructionSubmitRequest struct {

	NetworkIdentifier NetworkIdentifier `json:"network_identifier"`

	SignedTransaction string `json:"signed_transaction"`
}

// AssertConstructionSubmitRequestRequired checks if the required fields are not zero-ed
func AssertConstructionSubmitRequestRequired(obj ConstructionSubmitRequest) error {
	elements := map[string]interface{}{
		"network_identifier": obj.NetworkIdentifier,
		"signed_transaction": obj.SignedTransaction,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertNetworkIdentifierRequired(obj.NetworkIdentifier); err != nil {
		return err
	}
	return nil
}

// AssertConstructionSubmitRequestConstraints checks if the values respects the defined constraints
func AssertConstructionSubmitRequestConstraints(obj ConstructionSubmitRequest) error {
	if err := AssertNetworkIdentifierConstraints(obj.NetworkIdentifier); err != nil {
		return err
	}
	return nil
}
