// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// ConstructionCombineResponse - ConstructionCombineResponse is returned by `/construction/combine`. The network payload will be sent directly to the `construction/submit` endpoint.
type ConstructionCombineResponse struct {

	SignedTransaction string `json:"signed_transaction"`
}

// AssertConstructionCombineResponseRequired checks if the required fields are not zero-ed
func AssertConstructionCombineResponseRequired(obj ConstructionCombineResponse) error {
	elements := map[string]interface{}{
		"signed_transaction": obj.SignedTransaction,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertConstructionCombineResponseConstraints checks if the values respects the defined constraints
func AssertConstructionCombineResponseConstraints(obj ConstructionCombineResponse) error {
	return nil
}
