// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// NetworkListResponse - A NetworkListResponse contains all NetworkIdentifiers that the node can serve information for.
type NetworkListResponse struct {

	NetworkIdentifiers []NetworkIdentifier `json:"network_identifiers"`
}

// AssertNetworkListResponseRequired checks if the required fields are not zero-ed
func AssertNetworkListResponseRequired(obj NetworkListResponse) error {
	elements := map[string]interface{}{
		"network_identifiers": obj.NetworkIdentifiers,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.NetworkIdentifiers {
		if err := AssertNetworkIdentifierRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertNetworkListResponseConstraints checks if the values respects the defined constraints
func AssertNetworkListResponseConstraints(obj NetworkListResponse) error {
	for _, el := range obj.NetworkIdentifiers {
		if err := AssertNetworkIdentifierConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
