// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// ConstructionDeriveRequest - ConstructionDeriveRequest is passed to the `/construction/derive` endpoint. Network is provided in the request because some blockchains have different address formats for different networks. Metadata is provided in the request because some blockchains allow for multiple address types (i.e. different address for validators vs normal accounts).
type ConstructionDeriveRequest struct {

	NetworkIdentifier NetworkIdentifier `json:"network_identifier"`

	PublicKey PublicKey `json:"public_key"`

	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// AssertConstructionDeriveRequestRequired checks if the required fields are not zero-ed
func AssertConstructionDeriveRequestRequired(obj ConstructionDeriveRequest) error {
	elements := map[string]interface{}{
		"network_identifier": obj.NetworkIdentifier,
		"public_key": obj.PublicKey,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertNetworkIdentifierRequired(obj.NetworkIdentifier); err != nil {
		return err
	}
	if err := AssertPublicKeyRequired(obj.PublicKey); err != nil {
		return err
	}
	return nil
}

// AssertConstructionDeriveRequestConstraints checks if the values respects the defined constraints
func AssertConstructionDeriveRequestConstraints(obj ConstructionDeriveRequest) error {
	if err := AssertNetworkIdentifierConstraints(obj.NetworkIdentifier); err != nil {
		return err
	}
	if err := AssertPublicKeyConstraints(obj.PublicKey); err != nil {
		return err
	}
	return nil
}
