// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// TransactionIdentifier - The transaction_identifier uniquely identifies a transaction in a particular network and block or in the mempool.
type TransactionIdentifier struct {

	// Any transactions that are attributable only to a block (ex: a block event) should use the hash of the block as the identifier.  This should be normalized according to the case specified in the transaction_hash_case in network options.
	Hash string `json:"hash"`
}

// AssertTransactionIdentifierRequired checks if the required fields are not zero-ed
func AssertTransactionIdentifierRequired(obj TransactionIdentifier) error {
	elements := map[string]interface{}{
		"hash": obj.Hash,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertTransactionIdentifierConstraints checks if the values respects the defined constraints
func AssertTransactionIdentifierConstraints(obj TransactionIdentifier) error {
	return nil
}
