// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// BlockRequest - A BlockRequest is utilized to make a block request on the /block endpoint.
type BlockRequest struct {

	NetworkIdentifier NetworkIdentifier `json:"network_identifier"`

	BlockIdentifier PartialBlockIdentifier `json:"block_identifier"`
}

// AssertBlockRequestRequired checks if the required fields are not zero-ed
func AssertBlockRequestRequired(obj BlockRequest) error {
	elements := map[string]interface{}{
		"network_identifier": obj.NetworkIdentifier,
		"block_identifier": obj.BlockIdentifier,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertNetworkIdentifierRequired(obj.NetworkIdentifier); err != nil {
		return err
	}
	if err := AssertPartialBlockIdentifierRequired(obj.BlockIdentifier); err != nil {
		return err
	}
	return nil
}

// AssertBlockRequestConstraints checks if the values respects the defined constraints
func AssertBlockRequestConstraints(obj BlockRequest) error {
	if err := AssertNetworkIdentifierConstraints(obj.NetworkIdentifier); err != nil {
		return err
	}
	if err := AssertPartialBlockIdentifierConstraints(obj.BlockIdentifier); err != nil {
		return err
	}
	return nil
}
