// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// AccountBalanceRequest - An AccountBalanceRequest is utilized to make a balance request on the /account/balance endpoint. If the block_identifier is populated, a historical balance query should be performed.
type AccountBalanceRequest struct {

	NetworkIdentifier NetworkIdentifier `json:"network_identifier"`

	AccountIdentifier AccountIdentifier `json:"account_identifier"`

	BlockIdentifier PartialBlockIdentifier `json:"block_identifier,omitempty"`

	// In some cases, the caller may not want to retrieve all available balances for an AccountIdentifier. If the currencies field is populated, only balances for the specified currencies will be returned. If not populated, all available balances will be returned.
	Currencies []Currency `json:"currencies,omitempty"`
}

// AssertAccountBalanceRequestRequired checks if the required fields are not zero-ed
func AssertAccountBalanceRequestRequired(obj AccountBalanceRequest) error {
	elements := map[string]interface{}{
		"network_identifier": obj.NetworkIdentifier,
		"account_identifier": obj.AccountIdentifier,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertNetworkIdentifierRequired(obj.NetworkIdentifier); err != nil {
		return err
	}
	if err := AssertAccountIdentifierRequired(obj.AccountIdentifier); err != nil {
		return err
	}
	if err := AssertPartialBlockIdentifierRequired(obj.BlockIdentifier); err != nil {
		return err
	}
	for _, el := range obj.Currencies {
		if err := AssertCurrencyRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertAccountBalanceRequestConstraints checks if the values respects the defined constraints
func AssertAccountBalanceRequestConstraints(obj AccountBalanceRequest) error {
	if err := AssertNetworkIdentifierConstraints(obj.NetworkIdentifier); err != nil {
		return err
	}
	if err := AssertAccountIdentifierConstraints(obj.AccountIdentifier); err != nil {
		return err
	}
	if err := AssertPartialBlockIdentifierConstraints(obj.BlockIdentifier); err != nil {
		return err
	}
	for _, el := range obj.Currencies {
		if err := AssertCurrencyConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
