// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// Transaction - Transactions contain an array of Operations that are attributable to the same TransactionIdentifier.
type Transaction struct {

	TransactionIdentifier TransactionIdentifier `json:"transaction_identifier"`

	Operations []Operation `json:"operations"`

	RelatedTransactions []RelatedTransaction `json:"related_transactions,omitempty"`

	// Transactions that are related to other transactions (like a cross-shard transaction) should include the tranaction_identifier of these transactions in the metadata.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// AssertTransactionRequired checks if the required fields are not zero-ed
func AssertTransactionRequired(obj Transaction) error {
	elements := map[string]interface{}{
		"transaction_identifier": obj.TransactionIdentifier,
		"operations": obj.Operations,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertTransactionIdentifierRequired(obj.TransactionIdentifier); err != nil {
		return err
	}
	for _, el := range obj.Operations {
		if err := AssertOperationRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.RelatedTransactions {
		if err := AssertRelatedTransactionRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertTransactionConstraints checks if the values respects the defined constraints
func AssertTransactionConstraints(obj Transaction) error {
	if err := AssertTransactionIdentifierConstraints(obj.TransactionIdentifier); err != nil {
		return err
	}
	for _, el := range obj.Operations {
		if err := AssertOperationConstraints(el); err != nil {
			return err
		}
	}
	for _, el := range obj.RelatedTransactions {
		if err := AssertRelatedTransactionConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
