// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// Amount - Amount is some Value of a Currency. It is considered invalid to specify a Value without a Currency.
type Amount struct {

	// Value of the transaction in atomic units represented as an arbitrary-sized signed integer. For example, 1 BTC would be represented by a value of 100000000.
	Value string `json:"value"`

	Currency Currency `json:"currency"`

	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// AssertAmountRequired checks if the required fields are not zero-ed
func AssertAmountRequired(obj Amount) error {
	elements := map[string]interface{}{
		"value": obj.Value,
		"currency": obj.Currency,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertCurrencyRequired(obj.Currency); err != nil {
		return err
	}
	return nil
}

// AssertAmountConstraints checks if the values respects the defined constraints
func AssertAmountConstraints(obj Amount) error {
	if err := AssertCurrencyConstraints(obj.Currency); err != nil {
		return err
	}
	return nil
}
