// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi


import (
	"fmt"
)


// SignatureType : SignatureType is the type of a cryptographic signature. * ecdsa: `r (32-bytes) || s (32-bytes)` - `64 bytes` * ecdsa_recovery: `r (32-bytes) || s (32-bytes) || v (1-byte)` - `65 bytes` * ed25519: `R (32-byte) || s (32-bytes)` - `64 bytes` * schnorr_1: `r (32-bytes) || s (32-bytes)` - `64 bytes`  (schnorr signature implemented by Zilliqa where both `r` and `s` are scalars encoded as `32-bytes` values, most significant byte first.) * schnorr_bip340: `r (32-bytes) || s (32-bytes)` - `64 bytes`  (sig = (bytes(R) || bytes((k + ed) mod n) where `r` is the `X` coordinate of a point `R` whose `Y` coordinate is even, most significant bytes first.) * schnorr_poseidon: `r (32-bytes) || s (32-bytes)` where s = Hash(1st pk || 2nd pk || r) - `64 bytes`  (schnorr signature w/ Poseidon hash function implemented by O(1) Labs where both `r` and `s` are scalars encoded as `32-bytes` values, least significant byte first. https://github.com/CodaProtocol/signer-reference/blob/master/schnorr.ml )
type SignatureType string

// List of SignatureType
const (
	ECDSA SignatureType = "ecdsa"
	ECDSA_RECOVERY SignatureType = "ecdsa_recovery"
	ED25519 SignatureType = "ed25519"
	SCHNORR_1 SignatureType = "schnorr_1"
	SCHNORR_BIP340 SignatureType = "schnorr_bip340"
	SCHNORR_POSEIDON SignatureType = "schnorr_poseidon"
)

// AllowedSignatureTypeEnumValues is all the allowed values of SignatureType enum
var AllowedSignatureTypeEnumValues = []SignatureType{
	"ecdsa",
	"ecdsa_recovery",
	"ed25519",
	"schnorr_1",
	"schnorr_bip340",
	"schnorr_poseidon",
}

// validSignatureTypeEnumValue provides a map of SignatureTypes for fast verification of use input
var validSignatureTypeEnumValues = map[SignatureType]struct{}{
	"ecdsa": {},
	"ecdsa_recovery": {},
	"ed25519": {},
	"schnorr_1": {},
	"schnorr_bip340": {},
	"schnorr_poseidon": {},
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SignatureType) IsValid() bool {
	_, ok := validSignatureTypeEnumValues[v]
	return ok
}

// NewSignatureTypeFromValue returns a pointer to a valid SignatureType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSignatureTypeFromValue(v string) (SignatureType, error) {
	ev := SignatureType(v)
	if ev.IsValid() {
		return ev, nil
	}

	return "", fmt.Errorf("invalid value '%v' for SignatureType: valid values are %v", v, AllowedSignatureTypeEnumValues)
}



// AssertSignatureTypeRequired checks if the required fields are not zero-ed
func AssertSignatureTypeRequired(obj SignatureType) error {
	return nil
}

// AssertSignatureTypeConstraints checks if the values respects the defined constraints
func AssertSignatureTypeConstraints(obj SignatureType) error {
	return nil
}
