// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// AccountIdentifier - The account_identifier uniquely identifies an account within a network. All fields in the account_identifier are utilized to determine this uniqueness (including the metadata field, if populated).
type AccountIdentifier struct {

	// The address may be a cryptographic public key (or some encoding of it) or a provided username.
	Address string `json:"address"`

	SubAccount SubAccountIdentifier `json:"sub_account,omitempty"`

	// Blockchains that utilize a username model (where the address is not a derivative of a cryptographic public key) should specify the public key(s) owned by the address in metadata.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// AssertAccountIdentifierRequired checks if the required fields are not zero-ed
func AssertAccountIdentifierRequired(obj AccountIdentifier) error {
	elements := map[string]interface{}{
		"address": obj.Address,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertSubAccountIdentifierRequired(obj.SubAccount); err != nil {
		return err
	}
	return nil
}

// AssertAccountIdentifierConstraints checks if the values respects the defined constraints
func AssertAccountIdentifierConstraints(obj AccountIdentifier) error {
	if err := AssertSubAccountIdentifierConstraints(obj.SubAccount); err != nil {
		return err
	}
	return nil
}
