// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// Peer - A Peer is a representation of a node's peer.
type Peer struct {

	PeerId string `json:"peer_id"`

	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// AssertPeerRequired checks if the required fields are not zero-ed
func AssertPeerRequired(obj Peer) error {
	elements := map[string]interface{}{
		"peer_id": obj.PeerId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertPeerConstraints checks if the values respects the defined constraints
func AssertPeerConstraints(obj Peer) error {
	return nil
}
