// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// AccountCoinsResponse - AccountCoinsResponse is returned on the /account/coins endpoint and includes all unspent Coins owned by an AccountIdentifier.
type AccountCoinsResponse struct {

	BlockIdentifier BlockIdentifier `json:"block_identifier"`

	// If a blockchain is UTXO-based, all unspent Coins owned by an account_identifier should be returned alongside the balance. It is highly recommended to populate this field so that users of the Rosetta API implementation don't need to maintain their own indexer to track their UTXOs.
	Coins []Coin `json:"coins"`

	// Account-based blockchains that utilize a nonce or sequence number should include that number in the metadata. This number could be unique to the identifier or global across the account address.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// AssertAccountCoinsResponseRequired checks if the required fields are not zero-ed
func AssertAccountCoinsResponseRequired(obj AccountCoinsResponse) error {
	elements := map[string]interface{}{
		"block_identifier": obj.BlockIdentifier,
		"coins": obj.Coins,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertBlockIdentifierRequired(obj.BlockIdentifier); err != nil {
		return err
	}
	for _, el := range obj.Coins {
		if err := AssertCoinRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertAccountCoinsResponseConstraints checks if the values respects the defined constraints
func AssertAccountCoinsResponseConstraints(obj AccountCoinsResponse) error {
	if err := AssertBlockIdentifierConstraints(obj.BlockIdentifier); err != nil {
		return err
	}
	for _, el := range obj.Coins {
		if err := AssertCoinConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
