// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// ConstructionPreprocessResponse - ConstructionPreprocessResponse contains `options` that will be sent unmodified to `/construction/metadata`. If it is not necessary to make a request to `/construction/metadata`, `options` should be omitted.  Some blockchains require the PublicKey of particular AccountIdentifiers to construct a valid transaction. To fetch these PublicKeys, populate `required_public_keys` with the AccountIdentifiers associated with the desired PublicKeys. If it is not necessary to retrieve any PublicKeys for construction, `required_public_keys` should be omitted.
type ConstructionPreprocessResponse struct {

	// The options that will be sent directly to `/construction/metadata` by the caller.
	Options map[string]interface{} `json:"options,omitempty"`

	RequiredPublicKeys []AccountIdentifier `json:"required_public_keys,omitempty"`
}

// AssertConstructionPreprocessResponseRequired checks if the required fields are not zero-ed
func AssertConstructionPreprocessResponseRequired(obj ConstructionPreprocessResponse) error {
	for _, el := range obj.RequiredPublicKeys {
		if err := AssertAccountIdentifierRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertConstructionPreprocessResponseConstraints checks if the values respects the defined constraints
func AssertConstructionPreprocessResponseConstraints(obj ConstructionPreprocessResponse) error {
	for _, el := range obj.RequiredPublicKeys {
		if err := AssertAccountIdentifierConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
