// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi


import (
	"errors"
)



// Block - Blocks contain an array of Transactions that occurred at a particular BlockIdentifier. A hard requirement for blocks returned by Rosetta implementations is that they MUST be _inalterable_: once a client has requested and received a block identified by a specific BlockIndentifier, all future calls for that same BlockIdentifier must return the same block contents.
type Block struct {

	BlockIdentifier BlockIdentifier `json:"block_identifier"`

	ParentBlockIdentifier BlockIdentifier `json:"parent_block_identifier"`

	// The timestamp of the block in milliseconds since the Unix Epoch. The timestamp is stored in milliseconds because some blockchains produce blocks more often than once a second.
	Timestamp int64 `json:"timestamp"`

	Transactions []Transaction `json:"transactions"`

	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// AssertBlockRequired checks if the required fields are not zero-ed
func AssertBlockRequired(obj Block) error {
	elements := map[string]interface{}{
		"block_identifier": obj.BlockIdentifier,
		"parent_block_identifier": obj.ParentBlockIdentifier,
		"timestamp": obj.Timestamp,
		"transactions": obj.Transactions,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertBlockIdentifierRequired(obj.BlockIdentifier); err != nil {
		return err
	}
	if err := AssertBlockIdentifierRequired(obj.ParentBlockIdentifier); err != nil {
		return err
	}
	for _, el := range obj.Transactions {
		if err := AssertTransactionRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertBlockConstraints checks if the values respects the defined constraints
func AssertBlockConstraints(obj Block) error {
	if err := AssertBlockIdentifierConstraints(obj.BlockIdentifier); err != nil {
		return err
	}
	if err := AssertBlockIdentifierConstraints(obj.ParentBlockIdentifier); err != nil {
		return err
	}
	if obj.Timestamp < 0 {
		return &ParsingError{Param: "Timestamp", Err: errors.New(errMsgMinValueConstraint)}
	}
	for _, el := range obj.Transactions {
		if err := AssertTransactionConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
