// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// BlockResponse - A BlockResponse includes a fully-populated block or a partially-populated block with a list of other transactions to fetch (other_transactions). As a result of the consensus algorithm of some blockchains, blocks can be omitted (i.e. certain block indices can be skipped). If a query for one of these omitted indices is made, the response should not include a `Block` object. It is VERY important to note that blocks MUST still form a canonical, connected chain of blocks where each block has a unique index. In other words, the `PartialBlockIdentifier` of a block after an omitted block should reference the last non-omitted block.
type BlockResponse struct {

	Block Block `json:"block,omitempty"`

	// Some blockchains may require additional transactions to be fetched that weren't returned in the block response (ex: block only returns transaction hashes). For blockchains with a lot of transactions in each block, this can be very useful as consumers can concurrently fetch all transactions returned.
	OtherTransactions []TransactionIdentifier `json:"other_transactions,omitempty"`
}

// AssertBlockResponseRequired checks if the required fields are not zero-ed
func AssertBlockResponseRequired(obj BlockResponse) error {
	if err := AssertBlockRequired(obj.Block); err != nil {
		return err
	}
	for _, el := range obj.OtherTransactions {
		if err := AssertTransactionIdentifierRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertBlockResponseConstraints checks if the values respects the defined constraints
func AssertBlockResponseConstraints(obj BlockResponse) error {
	if err := AssertBlockConstraints(obj.Block); err != nil {
		return err
	}
	for _, el := range obj.OtherTransactions {
		if err := AssertTransactionIdentifierConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
