// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// ConstructionParseRequest - ConstructionParseRequest is the input to the `/construction/parse` endpoint. It allows the caller to parse either an unsigned or signed transaction.
type ConstructionParseRequest struct {

	NetworkIdentifier NetworkIdentifier `json:"network_identifier"`

	// Signed is a boolean indicating whether the transaction is signed.
	Signed bool `json:"signed"`

	// This must be either the unsigned transaction blob returned by `/construction/payloads` or the signed transaction blob returned by `/construction/combine`.
	Transaction string `json:"transaction"`
}

// AssertConstructionParseRequestRequired checks if the required fields are not zero-ed
func AssertConstructionParseRequestRequired(obj ConstructionParseRequest) error {
	elements := map[string]interface{}{
		"network_identifier": obj.NetworkIdentifier,
		"signed": obj.Signed,
		"transaction": obj.Transaction,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertNetworkIdentifierRequired(obj.NetworkIdentifier); err != nil {
		return err
	}
	return nil
}

// AssertConstructionParseRequestConstraints checks if the values respects the defined constraints
func AssertConstructionParseRequestConstraints(obj ConstructionParseRequest) error {
	if err := AssertNetworkIdentifierConstraints(obj.NetworkIdentifier); err != nil {
		return err
	}
	return nil
}
