// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi


import (
	"fmt"
)


// BlockEventType : BlockEventType determines if a BlockEvent represents the addition or removal of a block.
type BlockEventType string

// List of BlockEventType
const (
	BLOCK_ADDED BlockEventType = "block_added"
	BLOCK_REMOVED BlockEventType = "block_removed"
)

// AllowedBlockEventTypeEnumValues is all the allowed values of BlockEventType enum
var AllowedBlockEventTypeEnumValues = []BlockEventType{
	"block_added",
	"block_removed",
}

// validBlockEventTypeEnumValue provides a map of BlockEventTypes for fast verification of use input
var validBlockEventTypeEnumValues = map[BlockEventType]struct{}{
	"block_added": {},
	"block_removed": {},
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BlockEventType) IsValid() bool {
	_, ok := validBlockEventTypeEnumValues[v]
	return ok
}

// NewBlockEventTypeFromValue returns a pointer to a valid BlockEventType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBlockEventTypeFromValue(v string) (BlockEventType, error) {
	ev := BlockEventType(v)
	if ev.IsValid() {
		return ev, nil
	}

	return "", fmt.Errorf("invalid value '%v' for BlockEventType: valid values are %v", v, AllowedBlockEventTypeEnumValues)
}



// AssertBlockEventTypeRequired checks if the required fields are not zero-ed
func AssertBlockEventTypeRequired(obj BlockEventType) error {
	return nil
}

// AssertBlockEventTypeConstraints checks if the values respects the defined constraints
func AssertBlockEventTypeConstraints(obj BlockEventType) error {
	return nil
}
