// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// CallRequest - CallRequest is the input to the `/call` endpoint.
type CallRequest struct {

	NetworkIdentifier NetworkIdentifier `json:"network_identifier"`

	// Method is some network-specific procedure call. This method could map to a network-specific RPC endpoint, a method in an SDK generated from a smart contract, or some hybrid of the two. The implementation must define all available methods in the Allow object. However, it is up to the caller to determine which parameters to provide when invoking `/call`.
	Method string `json:"method"`

	// Parameters is some network-specific argument for a method. It is up to the caller to determine which parameters to provide when invoking `/call`.
	Parameters map[string]interface{} `json:"parameters"`
}

// AssertCallRequestRequired checks if the required fields are not zero-ed
func AssertCallRequestRequired(obj CallRequest) error {
	elements := map[string]interface{}{
		"network_identifier": obj.NetworkIdentifier,
		"method": obj.Method,
		"parameters": obj.Parameters,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertNetworkIdentifierRequired(obj.NetworkIdentifier); err != nil {
		return err
	}
	return nil
}

// AssertCallRequestConstraints checks if the values respects the defined constraints
func AssertCallRequestConstraints(obj CallRequest) error {
	if err := AssertNetworkIdentifierConstraints(obj.NetworkIdentifier); err != nil {
		return err
	}
	return nil
}
