// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi




// MetadataRequest - A MetadataRequest is utilized in any request where the only argument is optional metadata.
type MetadataRequest struct {

	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// AssertMetadataRequestRequired checks if the required fields are not zero-ed
func AssertMetadataRequestRequired(obj MetadataRequest) error {
	return nil
}

// AssertMetadataRequestConstraints checks if the values respects the defined constraints
func AssertMetadataRequestConstraints(obj MetadataRequest) error {
	return nil
}
