// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi


import (
	"fmt"
)


// CoinAction : CoinActions are different state changes that a Coin can undergo. When a Coin is created, it is coin_created. When a Coin is spent, it is coin_spent. It is assumed that a single Coin cannot be created or spent more than once.
type CoinAction string

// List of CoinAction
const (
	COIN_CREATED CoinAction = "coin_created"
	COIN_SPENT CoinAction = "coin_spent"
)

// AllowedCoinActionEnumValues is all the allowed values of CoinAction enum
var AllowedCoinActionEnumValues = []CoinAction{
	"coin_created",
	"coin_spent",
}

// validCoinActionEnumValue provides a map of CoinActions for fast verification of use input
var validCoinActionEnumValues = map[CoinAction]struct{}{
	"coin_created": {},
	"coin_spent": {},
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CoinAction) IsValid() bool {
	_, ok := validCoinActionEnumValues[v]
	return ok
}

// NewCoinActionFromValue returns a pointer to a valid CoinAction
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCoinActionFromValue(v string) (CoinAction, error) {
	ev := CoinAction(v)
	if ev.IsValid() {
		return ev, nil
	}

	return "", fmt.Errorf("invalid value '%v' for CoinAction: valid values are %v", v, AllowedCoinActionEnumValues)
}



// AssertCoinActionRequired checks if the required fields are not zero-ed
func AssertCoinActionRequired(obj CoinAction) error {
	return nil
}

// AssertCoinActionConstraints checks if the values respects the defined constraints
func AssertCoinActionConstraints(obj CoinAction) error {
	return nil
}
