// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.13
 */

package openapi


import (
	"errors"
)



// EventsBlocksRequest - EventsBlocksRequest is utilized to fetch a sequence of BlockEvents indicating which blocks were added and removed from storage to reach the current state.
type EventsBlocksRequest struct {

	NetworkIdentifier NetworkIdentifier `json:"network_identifier"`

	// offset is the offset into the event stream to sync events from. If this field is not populated, we return the limit events backwards from tip. If this is set to 0, we start from the beginning.
	Offset int64 `json:"offset,omitempty"`

	// limit is the maximum number of events to fetch in one call. The implementation may return <= limit events.
	Limit int64 `json:"limit,omitempty"`
}

// AssertEventsBlocksRequestRequired checks if the required fields are not zero-ed
func AssertEventsBlocksRequestRequired(obj EventsBlocksRequest) error {
	elements := map[string]interface{}{
		"network_identifier": obj.NetworkIdentifier,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertNetworkIdentifierRequired(obj.NetworkIdentifier); err != nil {
		return err
	}
	return nil
}

// AssertEventsBlocksRequestConstraints checks if the values respects the defined constraints
func AssertEventsBlocksRequestConstraints(obj EventsBlocksRequest) error {
	if err := AssertNetworkIdentifierConstraints(obj.NetworkIdentifier); err != nil {
		return err
	}
	if obj.Offset < 0 {
		return &ParsingError{Param: "Offset", Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.Limit < 0 {
		return &ParsingError{Param: "Limit", Err: errors.New(errMsgMinValueConstraint)}
	}
	return nil
}
