{
 "title": "Go-quai Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Usage System vs Go-quai",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "cpu_usage{usage_type=\"Go-quai\"}",
     "legendFormat": "{{usage_type}}"
    },
    {
     "expr": "cpu_usage{usage_type=\"System\"}",
     "legendFormat": "{{usage_type}}"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "I/O Wait",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "cpu_usage{usage_type=\"Iowait\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": " RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mem_usage{usage_type=\"Stack\"}",
     "legendFormat": "{{usage_type}}"
    },
    {
     "expr": "mem_usage{usage_type=\"Used\"}",
     "legendFormat": "{{usage_type}}"
    },
    {
     "expr": "mem_usage{usage_type=\"Swap\"}",
     "legendFormat": "{{usage_type}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Disk IO/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "disk_usage{usage_type!=\"Iops\"}",
     "legendFormat": "{{usage_type}}"
    }
   ]
  },
  {
   "title": "Number of IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "disk_usage{usage_type=\"Iops\"}",
     "legendFormat": "{{usage_type}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Number of Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    { "expr": "net_usage", "legendFormat": "{{net_type}}" }
   ]
  },
  { "title": "Internal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "State DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    { "expr": "StateTimes", "legendFormat": "{{label}}" }
   ]
  },
  {
   "title": "TxPool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    { "expr": "TxpoolGauges", "legendFormat": "{{label}}" }
   ]
  },
  {
   "title": "TxPool Weighted Moving Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "(\n    (avg_over_time(TxpoolGauges[5m]) * 0.4) + (avg_over_time(TxpoolGauges[15m]) * 0.3) + (avg_over_time(TxpoolGauges[30m]) * 0.2) + (avg_over_time(TxpoolGauges[1h]) * 0.1)\n)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "TxPool Moving Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "avg_over_time(TxpoolGauges[1h])",
     "legendFormat": "{{label}}"
    }
   ]
  }
 ]
}